const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {WorkspaceStore,KnowledgeStore,snapshot}=require('../src/advanced/store.cjs');
const {intent,suggestions,calculate,trackerHost,securitySummary}=require('../src/advanced/commands.cjs');
const {ProviderConfig,endpoint}=require('../src/ai-provider.cjs');const {Assistant}=require('../src/ai.cjs');const {DEFAULTS,sanitizeSettings}=require('../src/settings.cjs');const {validRoot}=require('../src/advanced/ghost.cjs');const {Diagnostics}=require('../src/advanced/diagnostics.cjs');
const temporary=t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'Kernel-Unit-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;};
const vault={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s.split('').reverse().join('')),decryptString:b=>b.toString().split('').reverse().join('')};
test('workspace migration and independent histories, settings, groups and tabs survive reload',t=>{
 const root=temporary(t),initial={tabs:[{url:'https://example.com',title:'Example',group:'g1'}],activeIndex:0,settings:{theme:'dark',accent:'#112233'},bookmarks:[{title:'Saved',url:'https://example.com'}],history:[{title:'Visited',url:'https://example.com',at:1}],groups:[{id:'g1',name:'Research'}]};
 const store=new WorkspaceStore(root,initial),first=store.active().id,second=store.create({name:'Work',icon:'W',accent:'#334455'},{settings:{theme:'light'}});
 assert.equal(second.history.length,0);store.select(second.id);store.capture({tabs:[{url:'https://work.test'}],settings:{theme:'light'}});
 const restored=new WorkspaceStore(root,{});assert.equal(restored.active().id,second.id);assert.equal(restored.active().tabs[0].url,'https://work.test');assert.equal(restored.select(first).history.length,1);assert.equal(restored.active().groups[0].name,'Research');assert.equal(restored.active().settings.theme,'dark');
 const copy=restored.duplicate(first);copy.settings.theme='light';assert.equal(restored.active().settings.theme,'dark');assert.throws(()=>restored.remove(first));restored.remove(second.id);assert.equal(restored.list().length,2);
});
test('workspace snapshots reject executable URLs and unsafe navigation entries',()=>{
 const s=snapshot({tabs:[{url:'javascript:alert(1)'},{url:'https://safe.test',navigation:{entries:[{url:'file:///private'},{url:'https://safe.test',title:'Safe',pageState:'state'}],index:99},scroll:{x:-1,y:Infinity}}]});assert.equal(s.tabs.length,1);assert.equal(s.tabs[0].navigation.entries.length,1);assert.equal(s.tabs[0].navigation.index,0);assert.equal(s.tabs[0].scroll.x,0);assert.ok(Number.isFinite(s.tabs[0].scroll.y));
});
test('notes are scoped, searchable by tags and editable without overwriting other notes',t=>{
 const root=temporary(t),store=new KnowledgeStore(root,{'https://legacy.test':'Legacy'}),a=store.note({text:'One',url:'https://one.test',selection:'Quote',workspace:'a',tags:['design']}),b=store.note({text:'Two',workspace:'b'});
 assert.equal(store.notes('', 'a').length,1);assert.equal(store.notes('design')[0].id,a.id);store.note({...a,text:'Changed'});const reloaded=new KnowledgeStore(root);assert.equal(reloaded.notes('changed')[0].selection,'Quote');assert.equal(reloaded.notes('', 'b')[0].id,b.id);reloaded.removeNote(a.id);assert.equal(reloaded.notes('design').length,0);assert.equal(reloaded.notes('Legacy').length,1);
});
test('capsules retain offline text and selected raster images and reject path traversal',t=>{
 const root=temporary(t),store=new KnowledgeStore(root),c=store.saveCapsule({title:'Offline',url:'https://test',text:'A useful article',notes:'My note',images:[{data:'data:image/png;base64,aGVsbG8='},{data:'data:image/svg+xml;base64,aGVsbG8='}]});
 const reloaded=new KnowledgeStore(root);assert.equal(reloaded.capsules('useful')[0].id,c.id);assert.equal(reloaded.capsule(c.id).images.length,1);assert.equal(reloaded.capsule(c.id).notes,'My note');assert.throws(()=>reloaded.capsule('../outside'));reloaded.removeCapsule(c.id);assert.equal(reloaded.capsules().length,0);
});
test('unified commands, scoped suggestions and safe arithmetic do not execute code',()=>{
 for(const c of ['tabs','history','bookmarks','settings','workspace','ai','privacy','performance','translate','summarize'])assert.equal(intent('/'+c+' hello').command,c);
 assert.equal(intent('tabs: github').query,'github');assert.equal(intent('Internal settings').command,'settings');assert.equal(intent('https://test/a').kind,'navigate');assert.equal(calculate('2*(3+4)^2'),98);assert.equal(calculate('2^3^2'),512);assert.equal(calculate('1/0'),null);assert.equal(calculate('process.exit()'),null);assert.equal(calculate('1 2+3'),null);
 const rows=suggestions('/tabs git',{tabs:[{id:'a',title:'GitHub',url:'https://github.com'},{id:'b',title:'Other',url:'https://other'}],history:[{title:'GitHub',url:'https://github.com'}]});assert.equal(rows.length,1);assert.equal(rows[0].id,'a');assert.equal(rows[0].type,'tabs');assert.equal(suggestions('/privacy')[0].command,'privacy');
});
test('tracker matching uses domain boundaries and security observations retain limitations',()=>{
 assert.equal(trackerHost('https://google-analytics.com/collect'),'google-analytics.com');assert.equal(trackerHost('https://google-analytics.com.attacker.test/'),null);assert.equal(trackerHost('https://facebook.com/profile'),null);assert.ok(trackerHost('https://www.facebook.com/tr?id=1'));
 const s=securitySummary({url:'https://test',headers:{'Content-Security-Policy':['default-src self']},cookies:[{name:'session',secure:true,httpOnly:true}]});assert.equal(s.https,true);assert.equal(s.headers['content-security-policy'],'default-src self');assert.ok(s.limitations);assert.equal(s.tls,null);
});
test('compatible provider protects API keys and requires remote consent before any context access',async t=>{
 const root=temporary(t),provider=new ProviderConfig(root,vault);assert.throws(()=>endpoint('http://external.test/v1'));assert.throws(()=>endpoint('https://user:password@example.test/v1'));assert.throws(()=>endpoint('https://test/v1?key=secret'));assert.equal(endpoint('http://127.0.0.1:123/v1').local,true);
 provider.configure({endpoint:'https://provider.example/v1',model:'my-model',key:'unit-secret'});assert.equal(provider.info().hasKey,true);assert.ok(!JSON.stringify(provider.info()).includes('unit-secret'));assert.ok(!fs.readFileSync(provider.file,'utf8').includes('unit-secret'));
 let reads=0;const assistant=new Assistant({vendor:root,bundledModels:root,userData:root,provider,emit:()=>{},pageContext:()=>{reads++;return{private:'text'};},options:{...DEFAULTS,aiProvider:'compatible'}});await assert.rejects(assistant.chat({messages:[{role:'user',content:'Hi'}],context:true}),/Подтвердите/);assert.equal(reads,0);assert.equal(assistant.controller,null);assert.equal(provider.connection(true).headers.Authorization,'Bearer unit-secret');
});
test('compatible local API streams with selected context and settings, without local inference startup',async t=>{
 const root=temporary(t);let received;const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;received=JSON.parse(body);assert.equal(req.url,'/v1/chat/completions');res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{delta:{content:'Hello'}}]})+'\n\ndata: [DONE]\n\n');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());
 const provider=new ProviderConfig(root,vault);provider.configure({endpoint:'http://127.0.0.1:'+server.address().port+'/v1',model:'test-model'});const tokens=[];const assistant=new Assistant({vendor:root,bundledModels:root,userData:root,provider,pageContext:input=>({pages:[{url:'https://selected.test',text:'Selected context'}],selected:input.tabIds}),emit:(event,value)=>{if(event==='ai-token')tokens.push(value);},options:{...DEFAULTS,aiProvider:'compatible',aiTemperature:0.2,aiMaxTokens:256}});
 const result=await assistant.chat({messages:[{role:'user',content:'Summarize'}],context:{tabIds:['one']}});assert.equal(result.text,'Hello');assert.deepEqual(tokens,['Hello']);assert.equal(received.model,'test-model');assert.equal(received.temperature,.2);assert.equal(received.max_tokens,256);assert.ok(received.messages.some(m=>m.content.includes('Selected context')));assert.equal(assistant.process,null);
});
test('new settings clamp resource limits and do not accept malformed routing or model paths',()=>{
 const s=sanitizeSettings({aiProvider:'bad',aiContext:999999,aiMaxTokens:Infinity,sleepMinutes:0,ghostRoute:'untrusted',aiModelFile:'C:/x.exe',siteTrackerBlocking:{'https://test/path':true,'file:///private':true,'https://bad':'yes'}});assert.equal(s.aiProvider,'local');assert.equal(s.aiContext,32768);assert.equal(s.aiMaxTokens,DEFAULTS.aiMaxTokens);assert.equal(s.sleepMinutes,1);assert.equal(s.ghostRoute,'direct');assert.equal(s.aiModelFile,'');assert.deepEqual(s.siteTrackerBlocking,{'https://test':true});
});
test('Ghost cleanup is limited to dedicated direct-child temporary directories',()=>{
 assert.equal(validRoot(path.join(os.tmpdir(),'Kernel-Ghost-abc123')),true);assert.equal(validRoot(os.tmpdir()),false);assert.equal(validRoot(path.join(os.tmpdir(),'Kernel-Ghost-abc123','child')),false);assert.equal(validRoot(path.join(os.tmpdir(),'NormalProfile')),false);
});
test('workspace-specific AI endpoints and encrypted credentials survive independent changes',t=>{
 const root=temporary(t),p=new ProviderConfig(root,vault,'first');p.configure({endpoint:'https://one.example/v1',model:'one',key:'private-key'});p.duplicate('first','second');p.select('second');p.configure({endpoint:'https://two.example/v1',model:'two'});p.select('first');assert.equal(p.info().model,'one');assert.equal(p.connection(true).headers.Authorization,'Bearer private-key');const restored=new ProviderConfig(root,vault,'second');assert.equal(restored.info().model,'two');assert.equal(restored.info().endpoint,'https://two.example/v1');assert.ok(!JSON.stringify(restored.document).includes('private-key'));assert.throws(()=>restored.select('__proto__'));
});
test('workspace and note corruption recovers the last backup without erasing damaged input',t=>{
 const root=temporary(t),w=new WorkspaceStore(root,{tabs:[{url:'https://preserved.test'}]});w.capture({tabs:[{url:'https://latest.test'}]});fs.writeFileSync(w.file,'{broken');const restored=new WorkspaceStore(root);assert.equal(restored.active().tabs[0].url,'https://preserved.test');assert.ok(fs.readdirSync(root).some(n=>n.startsWith('workspaces.json.corrupt-')));
 const notes=new KnowledgeStore(root);notes.note({text:'first'});notes.note({text:'second'});fs.writeFileSync(notes.file,'{broken');assert.equal(new KnowledgeStore(root).notes('first').length,1);const badRoot=path.join(root,'bad');fs.mkdirSync(badRoot);const file=path.join(badRoot,'knowledge.json');fs.writeFileSync(file,'{broken');assert.throws(()=>new KnowledgeStore(badRoot));assert.equal(fs.readFileSync(file,'utf8'),'{broken');
});
test('process metrics total unique Chromium processes rather than duplicated tab memory',()=>{
 const tabs=[{id:'a',title:'A',url:'https://a',view:{webContents:{isDestroyed:()=>false,getOSProcessId:()=>2,isCurrentlyAudible:()=>false}}},{id:'b',title:'B',url:'https://b',view:{webContents:{isDestroyed:()=>false,getOSProcessId:()=>2,isCurrentlyAudible:()=>false}}}],diagnostics=new Diagnostics({tabs,settings:()=>DEFAULTS}),app={getAppMetrics:()=>[{pid:1,type:'Browser',cpu:{percentCPUUsage:1},memory:{workingSetSize:100}},{pid:2,type:'Tab',cpu:{percentCPUUsage:2},memory:{workingSetSize:200}}],getGPUFeatureStatus:()=>({gpu_compositing:'enabled'})};const m=diagnostics.metrics(app,tabs,'a');assert.equal(m.ramKB,300);assert.equal(m.cpu,3);assert.equal(m.tabs[0].ramKB,200);assert.equal(m.tabs[1].ramKB,200);
});
test('AI action proposals accept only bounded whitelisted browser operations',()=>{
 const {action,SCHEMAS}=require('../src/ai-actions.cjs');assert.equal(action('execute_shell',{command:'bad'}),null);assert.equal(action('sleep_tab',{url:'javascript:alert(1)'}),null);assert.equal(action('save_note',{text:'A note',tags:['design']}).kind,'save_note');assert.equal(action('save_note',{text:'x'.repeat(30000)}).args.text.length,20000);assert.equal(action('switch_workspace',{name:'Research'}).args.name,'Research');assert.equal(SCHEMAS.length,4);
});
test('API redirects cannot forward selected private context to another endpoint',async t=>{
 const root=temporary(t);let leaked=false;const server=http.createServer((req,res)=>{if(req.url==='/leak'){leaked=true;res.end();return;}res.writeHead(307,{Location:'/leak'});res.end();});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const provider=new ProviderConfig(root,vault);provider.configure({endpoint:'http://127.0.0.1:'+server.address().port+'/v1',model:'test'});const assistant=new Assistant({vendor:root,bundledModels:root,userData:root,provider,emit:()=>{},pageContext:()=>({text:'private context'}),options:{...DEFAULTS,aiProvider:'compatible'}});await assert.rejects(assistant.chat({messages:[{role:'user',content:'Hi'}],context:true}));assert.equal(leaked,false);
});
test('tracker blocking preserves top-level navigation and obeys per-origin exceptions',()=>{
 let before;const ses={webRequest:{onBeforeRequest:fn=>before=fn,onHeadersReceived:()=>{}}},tabs=[{id:'tab',url:'https://site.test',view:{webContents:{id:8}}}],settings={...DEFAULTS,trackerBlocking:true,siteTrackerBlocking:{}},d=new Diagnostics({tabs,settings:()=>settings});d.attach(ses);const request={webContentsId:8,url:'https://google-analytics.com/collect',resourceType:'script'};let result;before(request,r=>result=r);assert.equal(result.cancel,true);before({...request,resourceType:'mainFrame'},r=>result=r);assert.equal(result.cancel,false);settings.siteTrackerBlocking['https://site.test']=false;before(request,r=>result=r);assert.equal(result.cancel,false);assert.equal(d.record('tab').blocked,1);
});
test('the 12B default model is shared between local profiles while custom GGUF stays selectable',t=>{
 const root=temporary(t),shared=path.join(root,'shared'),user=path.join(root,'account');fs.mkdirSync(shared);fs.mkdirSync(user);const model=require('../src/model.cjs');assert.equal(model.parameters,'12B');assert.equal(model.bytes,7477208192);const file=path.join(shared,model.file);fs.writeFileSync(file,'partial');const a=new Assistant({vendor:root,bundledModels:path.join(root,'bundled'),sharedModels:shared,userData:user,emit:()=>{}});assert.equal(a.modelPath(),file);assert.equal(a.info().installed,false);const custom=path.join(root,'custom.gguf');a.configure({aiModelFile:custom});assert.equal(a.modelPath(),custom);assert.equal(a.info().model,'custom.gguf');
});
test('local model history keeps alternating roles after truncation or cancelled replies',()=>{
 const {normalizedHistory}=require('../src/ai.cjs'),input=Array.from({length:13},(_,i)=>({role:i%2?'assistant':'user',content:'message '+i}));const h=normalizedHistory(input);assert.equal(h[0].role,'user');assert.equal(h[h.length-1].role,'user');for(let i=1;i<h.length;i++)assert.notEqual(h[i].role,h[i-1].role);assert.deepEqual(normalizedHistory([{role:'assistant',content:'orphan'},{role:'user',content:'cancelled'},{role:'user',content:'retry'}]),[{role:'user',content:'cancelled\n\nretry'}]);
});
