const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));const until=async(fn,timeout=20000)=>{const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await delay(80);}throw Error('Timed out');};
exports.fixture=()=>http.createServer(async(req,res)=>{
 if(req.url==='/redirect'){res.writeHead(302,{Location:'/article'});res.end();return;}
 if(req.url==='/image.png'){res.writeHead(200,{'Content-Type':'image/png'});res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l6sAAAAASUVORK5CYII=','base64'));return;}
 if(req.url==='/v1/chat/completions'){let body='';for await(const chunk of req)body+=chunk;const input=JSON.parse(body);res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{delta:{content:'Fixture response: '+(input.messages.some(m=>m.content.includes('Capsule content'))?'context received':'no context')}}]})+'\n\ndata: [DONE]\n\n');return;}
 res.writeHead(200,{'Content-Type':'text/html;charset=utf-8','Content-Security-Policy':"default-src 'self'; style-src 'unsafe-inline' 'self'; script-src 'unsafe-inline' 'self' https://google-analytics.com; connect-src 'self' https://google-analytics.com; img-src 'self'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});res.end('<!doctype html><title>Advanced Fixture</title><article><h1>Advanced Fixture</h1><p>'+('Capsule content for integration checks. '.repeat(80))+'</p><a href="/next">Next</a><img src="/image.png"><input id="draft" value="original"><select><option>Default</option><option>Other</option></select><div style="height:2000px">Bottom</div></article>');
});
exports.restart=async(api,log)=>{const expected=JSON.parse(fs.readFileSync(path.join(api.rootData,'restart-expected.json')));assert.equal(api.workspaces.data.activeId,expected.workspace);assert.equal(api.state().tabs.length,expected.tabCount);assert.equal(api.state().settings.fontSize,14);assert.ok(api.knowledge.notes('integration-note').length);assert.ok(api.knowledge.capsules('Fixture').length);assert.ok(api.workspaces.active().groups.length);assert.equal(api.workspaces.list().length,expected.workspaceCount);log('Full restart restores workspace, groups, tabs, settings, notes and capsules');};
exports.run=async(api,report,log,origin)=>{
 const {app,win,tabs,advanced,workspaces,knowledge,safeSleep,switchWorkspace,rootData}=api;
 const js=code=>win.webContents.executeJavaScript(code,true),call=(name,input={})=>js('window.kernel.call("advanced",'+JSON.stringify({name,input})+')');
 assert.ok(await js('!!window.kernelAdvanced'));assert.ok(workspaces.active());log('Existing profile migrates without replacing browser chrome');
 const t0=performance.now(),firstId=api.createTab(origin+'/article'),first=tabs.find(t=>t.id===firstId);await until(()=>first.view&&!first.loading&&first.title==='Advanced Fixture');const firstWC=first.view.webContents;report.fixtureNavigationMs=performance.now()-t0;
 await firstWC.session.cookies.set({url:origin,name:'normal-only',value:'persistent',httpOnly:true});await firstWC.executeJavaScript('localStorage.setItem("normal-only","persistent");scrollTo(0,400)');await js('localStorage.setItem("normal-only","persistent")');
 const secondId=api.createTab(origin+'/other'),second=tabs.find(t=>t.id===secondId);await until(()=>second.view&&!second.loading&&second.title==='Advanced Fixture');
 assert.equal((await safeSleep(second)).slept,false);first.pinned=true;assert.equal((await safeSleep(first)).slept,false);first.pinned=false;
 await firstWC.executeJavaScript('document.getElementById("draft").value="unsaved"');assert.equal((await safeSleep(first)).slept,false);const originalWorkspace=workspaces.data.activeId,otherWorkspace=workspaces.create({name:'Independent',icon:'I',accent:'#8490a0'},{settings:api.state().settings});await assert.rejects(switchWorkspace(otherWorkspace.id),/Сохраните/);assert.equal(workspaces.data.activeId,originalWorkspace);await firstWC.executeJavaScript('document.getElementById("draft").value="original"');log('Active tabs, pins and unsaved forms are protected from discard and workspace changes');
 await firstWC.loadURL(origin+'/next');await until(()=>!first.loading);await firstWC.executeJavaScript('scrollTo(0,400)');assert.equal((await safeSleep(first)).slept,true);assert.equal(first.view,null);report.savedScroll=first.scroll;api.selectTab(firstId);await until(()=>first.view&&!first.loading&&first.title==='Advanced Fixture');assert.ok(first.view.webContents.navigationHistory.length()>=2);await until(()=>first.view.webContents.executeJavaScript('scrollY>=350'));log('Safe sleep frees a real WebContents and restores navigation history and scroll');
 const search=await call('tabs:search',{query:'Capsule content'});assert.ok(search.items.some(t=>t.id===firstId));await call('tabs:group-auto');assert.ok(workspaces.active().groups.length);await call('tabs:sort',{by:'title'});log('Loaded page search, domain grouping and sorting use actual tabs');
 const note=await call('notes:save',{text:'integration-note',tags:['fixture'],selection:'selected fragment'});assert.equal(note.workspace,originalWorkspace);assert.equal(knowledge.notes('fixture',originalWorkspace).length,1);
 const images=await call('capsules:images');assert.ok(images.some(i=>i.url.endsWith('/image.png')));const capsule=await call('capsules:save',{notes:'offline annotation',images:[origin+'/image.png']});assert.ok(capsule.text.includes('Capsule content'));assert.equal(capsule.images.length,1);assert.equal((await call('capsules:open',{id:capsule.id})).notes,'offline annotation');log('Notes and capsules persist real article text and selected images');
 const privacy=await call('privacy:get');assert.equal(privacy.cookieCount,1);assert.equal(privacy.security.headers['x-content-type-options'],'nosniff');assert.equal(privacy.security.https,false);await call('privacy:block',{enabled:true});await first.view.webContents.executeJavaScript('fetch("https://google-analytics.com/collect").catch(()=>null)');assert.ok((await call('privacy:get')).blocked>=1);api.applyBrowserSettings({sitePermissions:{[origin]:{media:'allow'}}});await call('privacy:reset');assert.deepEqual(api.state().settings.sitePermissions,{});log('Privacy center observes headers/cookies, blocks a tracker request and resets site permissions');
 const metrics=await call('performance:get');assert.ok(metrics.ramKB>0);assert.ok(metrics.tabs.some(t=>t.id===firstId&&t.pid>0));assert.ok(metrics.processes.length>0);log('Performance center reports real Chromium PIDs, CPU and resident RAM');
 const context=await api.pageContext({tabIds:[firstId]});assert.equal(context.pages.length,1);assert.ok(context.pages[0].text.includes('Capsule content'));api.provider.configure({endpoint:origin+'/v1',model:'fixture-model'});api.applyBrowserSettings({aiProvider:'compatible',aiMaxTokens:256});const answer=await api.assistant.chat({messages:[{role:'user',content:'Summarize'}],context:{tabIds:[firstId]}});assert.match(answer.text,/context received/);api.applyBrowserSettings({aiProvider:'local'});log('Provider interface streams a real HTTP API reply using selected tab context');
 await js('window.kernelAdvanced.open("tabs")');await until(()=>api.state().panel==='advanced');await delay(100);assert.equal(await js('document.getElementById("advanced-panel").classList.contains("hidden")'),false);
 for(const section of ['notes','capsules','privacy','security','performance','workspaces']){await js('window.kernelAdvanced.open('+JSON.stringify(section)+')');await delay(100);assert.ok(await js('document.querySelector(".advanced-content").textContent.length>10'));fs.writeFileSync(path.join(rootData,section+'-preview.png'),(await win.webContents.capturePage()).toPNG());}
 await js('window.kernelTools.openPalette();document.getElementById("command-query").value="/tabs Fixture";document.getElementById("command-query").dispatchEvent(new Event("input"))');await until(()=>js('[...document.querySelectorAll("#command-results button")].length===2&&[...document.querySelectorAll("#command-results button")].every(b=>b.textContent.includes("Advanced Fixture"))'));await js('document.getElementById("command-query").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",bubbles:true}));document.getElementById("command-query").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}))');await until(()=>!api.state().utilityOverlay&&api.state().activeId===secondId);log('Management panels and command-palette keyboard selection work through IPC');
 api.selectTab(firstId);await js('document.getElementById("address").focus();document.getElementById("address").value="/tabs Fixture";document.getElementById("address").dispatchEvent(new Event("input"))');await until(()=>js('document.querySelectorAll("#address-suggestions button").length===2'));await js('document.getElementById("address").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",bubbles:true,cancelable:true}));document.getElementById("address").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}))');await until(()=>api.state().activeId===secondId&&!api.state().utilityOverlay);await js('window.kernel.call("command:run",{type:"calculator",value:"14"})');assert.equal(await require('electron').clipboard.readText(),'14');log('Address autocomplete selects scoped tabs with keyboard; calculator copies a result');
 const liveBefore=require('electron').webContents.getAllWebContents().length;for(let i=0;i<6;i++){const id=api.createTab(origin+'/?lifecycle='+i),t=tabs.find(t=>t.id===id);await until(()=>t.view&&!t.loading&&t.title==='Advanced Fixture');await advanced.tools.startNetwork();api.closeTab(id);}await until(()=>require('electron').webContents.getAllWebContents().length<=liveBefore);assert.equal(advanced.tools.networkHandlers.size,0);assert.equal(advanced.tools.network.size,0);log('Repeated tab creation/close releases WebContents and API-recording handlers');
 api.applyBrowserSettings({fontSize:14});await switchWorkspace(otherWorkspace.id);assert.equal(api.state().history.length,0);assert.equal(knowledge.notes('',otherWorkspace.id).length,0);api.createTab('kernel://newtab');api.applyBrowserSettings({fontSize:15});await switchWorkspace(originalWorkspace);assert.equal(api.state().settings.fontSize,14);assert.ok(api.state().history.length);assert.ok(api.state().tabs.some(t=>t.url.startsWith(origin)));log('Workspace switching isolates tabs, history, notes and settings');
 api.selectTab(tabs.find(t=>t.url.startsWith(origin)).id);await until(()=>tabs.find(t=>t.id===api.state().activeId)?.view&&!tabs.find(t=>t.id===api.state().activeId).loading);const normalSession=tabs.find(t=>t.id===api.state().activeId).view.webContents.session;
 const ghostReport=path.join(rootData,'ghost-report.json');process.env.KERNEL_GHOST_FIXTURE=origin;process.env.KERNEL_GHOST_REPORT=ghostReport;let ghostRoot,ghostCode;
 const exited=new Promise((resolve,reject)=>require('../src/advanced/ghost.cjs').launchGhost(app,false,{smoke:true,background:true,onSpawn(root,child){ghostRoot=root;child.once('exit',code=>{ghostCode=code;resolve();});child.once('error',reject);}}));let timer;try{await Promise.race([exited,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('Ghost process did not exit')),25000))]);}finally{clearTimeout(timer);delete process.env.KERNEL_GHOST_FIXTURE;delete process.env.KERNEL_GHOST_REPORT;}const ghost=JSON.parse(fs.readFileSync(ghostReport));assert.equal(ghost.ok,true,ghost.error);assert.equal(ghostCode,0);await until(()=>!fs.existsSync(ghostRoot));assert.equal((await normalSession.cookies.get({url:origin})).some(c=>c.name==='normal-only'),true);assert.equal((await normalSession.cookies.get({url:origin})).some(c=>c.name==='ghost-only'),false);assert.equal(await js('localStorage.getItem("normal-only")'),'persistent');log('Separate Ghost process isolates cookies/UI storage, then removes its temporary directory');
 await call('privacy:clear',{cookiesOnly:true});assert.equal((await normalSession.cookies.get({url:origin})).length,0);log('Current-site cookie clearing leaves browser UI storage intact');
 const active=tabs.find(t=>t.id===api.state().activeId);active.view.webContents.forcefullyCrashRenderer();await until(()=>!!active.error);active.view.webContents.reload();await until(()=>!active.error&&!active.loading);log('Crashed page renderer recovers through reload without crashing browser chrome');
 const blank=api.createTab('kernel://newtab');api.selectTab(blank);await js('window.kernel.call("panel","")');await delay(350);fs.writeFileSync(path.join(rootData,'restart-expected.json'),JSON.stringify({workspace:originalWorkspace,tabCount:tabs.length,workspaceCount:workspaces.list().length}));fs.writeFileSync(path.join(rootData,'advanced-preview.png'),(await win.webContents.capturePage()).toPNG());report.knowledgeFile=knowledge.file;report.workspaceFile=workspaces.file;
};
