const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),net=require('node:net'),crypto=require('node:crypto');
const {resolvePolicy,profileFor,failover,validateProxy}=require('../src/connection/policy.cjs'),{ConnectionManager}=require('../src/connection/manager.cjs'),{ProxyProvider}=require('../src/connection/providers.cjs'),{cleanURL,textDiff,convert,safeName}=require('../src/tools/pure.cjs');
test('routing priority: explicit tab > exact site > workspace > global; Smart applies rules without guessing domains',()=>{const c={url:'https://youtube.com/watch',sites:{'youtube.com':{mode:'tunnel',profileId:'tor'}},workspace:{mode:'proxy'},global:{mode:'direct'}};assert.equal(resolvePolicy(c).mode,'tunnel');assert.equal(resolvePolicy({...c,tab:{mode:'direct'}}).mode,'direct');assert.equal(resolvePolicy({...c,tab:{mode:'smart'}}).mode,'tunnel');assert.equal(resolvePolicy({...c,url:'https://notyoutube.com'}).mode,'proxy');assert.equal(resolvePolicy({...c,workspace:null,url:'https://sub.youtube.com'}).mode,'direct');assert.equal(resolvePolicy({url:c.url,global:{mode:'smart'}}).mode,'direct');assert.equal(resolvePolicy({...c,sites:{'youtube.com':{mode:'tunnel',enabled:false}}}).mode,'proxy');});
test('profile selection and fallback do not invent endpoints or silently choose Direct',()=>{const profiles=[{id:'tor',type:'tor'},{id:'snowflake',type:'tor'},{id:'proxy',type:'http'}];assert.equal(profileFor({mode:'tunnel'},profiles).id,'tor');assert.equal(profileFor({mode:'proxy',profileId:'missing'},profiles),null);assert.equal(failover({mode:'tunnel'},profiles,'tor',true).id,'snowflake');assert.equal(failover({mode:'proxy'},profiles,'proxy',true),null);assert.equal(failover({mode:'tunnel'},profiles,'tor',false),null);assert.throws(()=>validateProxy({type:'http',host:'example.com; command',port:80}));assert.throws(()=>validateProxy({type:'http',host:'example.com',port:65536}));});
function store(){const root=fs.mkdtempSync(path.resolve(__dirname,'../../routing-test-'));const key=crypto.randomBytes(32),vault={isEncryptionAvailable:()=>true,encryptString(t){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(t),c.final(),c.getAuthTag()]);},decryptString(b){const d=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString();}};const contexts=new Map(),session={fromPartition(name){if(!contexts.has(name))contexts.set(name,{name,async setProxy(p){this.proxy=p;},async closeAllConnections(){}});return contexts.get(name);}};return{root,basePartition:'persist:test',vault,session,vendor:'',changed(){},setup(){}};}
test('VPN off overrides tab, site and workspace rules, stops providers and persists without deleting routes',async()=>{
  const options=store(),m=new ConnectionManager(options);let stops=0;
  try{m.global={mode:'tunnel',profileId:'tor'};m.workspace={mode:'proxy',profileId:'saved'};m.sites['example.com']={mode:'tunnel',profileId:'tor-snowflake'};m.tabs.set('tab',{mode:'tunnel',profileId:'tor'});m.providers.set('tor',{stop(){stops++;}});
    const routed=options.session.fromPartition('persist:test-route-tor');m.contexts.set('tor',{session:routed,generation:0});
    await m.setEnabled(false);assert.equal(stops,1);assert.equal(m.providers.size,0);assert.equal(routed.proxy.mode,'direct');
    for(const [id,url]of [['tab','https://example.com'],['new','https://example.com'],['new','https://other.com']])assert.equal(m.policy(id,url).mode,'direct');
    m.workspace={mode:'tunnel',profileId:'tor'};assert.equal(m.policy('new','https://another.com').mode,'direct');m.save();
    const restored=new ConnectionManager(options);try{assert.equal(restored.enabled,false);assert.equal(restored.policy('new','https://example.com').mode,'direct');assert.equal(restored.info('new','https://example.com').routingActive,false);await restored.setEnabled(true);assert.equal(restored.policy('new','https://example.com').profileId,'tor-snowflake');}finally{restored.dispose();}
    assert.equal(m.sites['example.com'].profileId,'tor-snowflake');assert.equal(m.tabs.get('tab').profileId,'tor');await assert.rejects(m.setEnabled('false'),/Неверное/);
  }finally{m.dispose();}
});
test('switching VPN off cancels pending startup without a fallback or a late proxy connection',async()=>{
  const m=new ConnectionManager(store());let finish,stops=0;try{const id=m.saveProxy({type:'http',host:'localhost',port:1234});m.assign({tabId:'a',url:'https://example.com',mode:'proxy',profileId:id});m.providers.set(id,{start(){return new Promise(resolve=>finish=resolve);},stop(){stops++;}});
    const pending=m.prepare('a','https://example.com');await new Promise(r=>setImmediate(r));await m.setEnabled(false);finish(4321);await assert.rejects(pending,/Маршрут изменён/);assert.ok(stops>=1);assert.equal(m.contexts.get(id).session.proxy.mode,'direct');assert.equal(m.policy('a','https://example.com').mode,'direct');assert.equal(m.tabs.get('a').profileId,id);
  }finally{m.dispose();}
});
test('site rules and encrypted proxy profiles survive restart without exposing secrets to UI',()=>{const options=store(),m=new ConnectionManager(options);try{const id=m.saveProxy({name:'Proxy',type:'socks5',host:'localhost',port:1080,username:'private-user',password:'private-password'});m.assign({tabId:'one',url:'https://example.com',mode:'proxy',profileId:id,scope:'site'});const disk=fs.readFileSync(m.file,'utf8');assert.ok(!disk.includes('private-password'));assert.ok(!disk.includes('private-user'));assert.ok(!JSON.stringify(m.info('one','https://example.com')).includes('private-password'));const restored=new ConnectionManager(options);try{assert.equal(restored.policy('two','https://example.com').profileId,id);assert.equal(restored.secret(restored.profiles.find(p=>p.id===id)).password,'private-password');}finally{restored.dispose();}}finally{m.dispose();}});
test('kill switch blocks failed proxy routes in their own session',async()=>{const m=new ConnectionManager(store());try{m.options.autoFallback=false;const id=m.saveProxy({type:'http',host:'127.0.0.1',port:1});m.assign({tabId:'a',url:'https://example.com',mode:'proxy',profileId:id});await assert.rejects(m.prepare('a','https://example.com'));assert.equal(m.policy('a','https://example.com').mode,'proxy');const s=m.session.fromPartition(m.partitionFor('a','https://example.com'));assert.match(s.proxy.proxyRules,/127\.0\.0\.1:1/);assert.equal(m.state('a','https://example.com').state,'failed');}finally{m.dispose();}});
test('authenticated HTTP gateway forwards requests without putting credentials in origin headers',async()=>{let authenticated=false;const upstream=http.createServer((req,res)=>{authenticated=req.headers['proxy-authorization']==='Basic '+Buffer.from('user:secret').toString('base64');res.end(authenticated?'proxy-result':'unauthorized');});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));const provider=new ProxyProvider({type:'http',host:'127.0.0.1',port:upstream.address().port},{username:'user',password:'secret'});try{const port=await provider.start();const text=await new Promise((resolve,reject)=>{http.get({hostname:'127.0.0.1',port,path:'http://example.test/resource'},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>resolve(s));}).on('error',reject);});assert.equal(text,'proxy-result');assert.ok(authenticated);}finally{provider.stop();upstream.closeAllConnections();await new Promise(r=>upstream.close(r));}});
test('clean links, text differences and conversions have deterministic useful results',()=>{assert.equal(cleanURL('https://example.com/?utm_source=x&keep=1&fbclid=x'),'https://example.com/?keep=1');assert.deepEqual(textDiff('one\ntwo','one\nthree').added,['three']);assert.equal(convert('base64:decode',convert('base64:encode','Привет')),'Привет');assert.equal(convert('km:m','1.5'),'1500');assert.equal(convert('c:f','0'),'32');assert.equal(convert('date:iso','0'),'1970-01-01T00:00:00.000Z');assert.ok(!/[<>:"/\\|?*]/.test(safeName('../site:copy')));});
test('Direct fallback requires explicit disabling of Kill Switch',async()=>{const m=new ConnectionManager(store());try{m.options.autoFallback=false;m.options.killSwitch=false;const id=m.saveProxy({type:'http',host:'127.0.0.1',port:1});m.assign({tabId:'a',url:'https://example.com',mode:'proxy',profileId:id});const ses=await m.prepare('a','https://example.com');assert.equal(ses.name,'persist:test');assert.equal(m.policy('a','https://example.com').mode,'direct');}finally{m.dispose();}});
test('two simultaneous tabs share a single startup and never leave the session in its initial blocked state',async()=>{const m=new ConnectionManager(store());let starts=0;try{const id=m.saveProxy({type:'http',host:'localhost',port:1234});for(const tabId of ['a','b'])m.assign({tabId,url:'https://example.com',mode:'proxy',profileId:id});m.providers.set(id,{async start(){starts++;await new Promise(r=>setTimeout(r,20));return 4321;},stop(){}});const [a,b]=await Promise.all([m.prepare('a','https://example.com'),m.prepare('b','https://example.com')]);assert.equal(a,b);assert.equal(starts,1);assert.match(a.proxy.proxyRules,/:4321/);}finally{m.dispose();}});
test('cancelling an in-flight route cannot overwrite the user selection with automatic fallback',async()=>{const m=new ConnectionManager(store());try{const id=m.saveProxy({type:'http',host:'localhost',port:1234});m.assign({tabId:'a',url:'https://example.com',mode:'proxy',profileId:id});let reject;m.providers.set(id,{start(){return new Promise((_r,j)=>reject=j);},stop(){reject?.(Error('stopped'));}});const pending=m.prepare('a','https://example.com');await new Promise(r=>setImmediate(r));m.assign({tabId:'a',url:'https://example.com',mode:'direct'});await assert.rejects(pending,/Маршрут изменён/);assert.equal(m.policy('a','https://example.com').mode,'direct');}finally{m.dispose();}});

