const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn, timeout=15000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await fn())return;await delay(100);}throw new Error('Timed out');}
exports.run=async api=>{
  const report=[]; const {win,tabs,assistant}=api; let server;
  const output=process.env.KERNEL_TEST_OUTPUT || path.resolve(__dirname,'../../../outputs');fs.mkdirSync(output,{recursive:true});
  const log=s=>{report.push(s);console.log('PASS '+s);};
  try{
    const errors=[];win.webContents.on('console-message',(_event,details)=>{if(details.level==='error')errors.push(details.message);});
    await until(()=>win.webContents.executeJavaScript('!!document.querySelector("#tabs .tab")'));
    assert.equal(await win.webContents.executeJavaScript('typeof window.kernel.call'),'function');log('Preload bridge and Russian UI loaded');
    assert.equal(await win.webContents.executeJavaScript('document.getElementById("side-panel").classList.contains("hidden")'),true);log('Assistant panel is hidden on startup');
    assert.equal(await win.webContents.executeJavaScript('document.querySelector(".sidebar [data-action=ai]")'),null);assert.equal(await win.webContents.executeJavaScript('!document.querySelector("#account-dev").classList.contains("hidden")'),api.accounts.info().developer);assert.equal(await win.webContents.executeJavaScript('document.querySelector("#account-name").textContent'),api.accounts.info().name);
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.querySelector(".toolbar")).height'),'48px');assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.querySelector(".rail")).width'),'38px');
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.querySelector("#pinned-tabs .tab")).width'),'32px');log('Compact browser chrome, pinned icons and account footer render; DEV is limited to a verified owner');
    await delay(900);
    fs.writeFileSync(path.join(output,'Kernel-preview.png'),(await win.webContents.capturePage()).toPNG());
    server=http.createServer((req,res)=>{
      if(req.url==='/favicon.png'){res.setHeader('Content-Type','image/png');res.end(fs.readFileSync(path.join(__dirname,'../assets/kernel.png')));return;}
      if(req.url==='/file'){res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition','attachment; filename="kernel-test.txt"');res.end('Kernel download works');return;}
      res.setHeader('Content-Type','text/html;charset=utf-8');
      if(req.url==='/two')res.end('<html><head><title>Second page</title></head><body><h1>Вторая страница</h1></body></html>');
      else if(req.url==='/security')res.end('<html><head><title>Security</title></head><body><script>document.body.dataset.node=typeof require;document.body.dataset.bridge=typeof window.kernel</script><h1>Remote isolation</h1></body></html>');
      else res.end('<html lang="ru"><head><title>Kernel Test</title><link rel="icon" href="/favicon.png"></head><body><h1>Тест браузера Kernel</h1><p>Столица Франции — Париж. Эта страница нужна для проверки локального помощника.</p><a id="next" href="/two">Дальше</a><a id="popup" target="_blank" href="/security">Новая вкладка</a></body></html>');
    });await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
    const id=api.createTab(origin);await until(()=>tabs.find(t=>t.id===id)?.title==='Kernel Test');
    let t=tabs.find(t=>t.id===id);assert.ok(t.view);assert.equal(t.view.webContents.getURL(),origin+'/');log('Real Chromium page loads in WebContentsView');
    api.pinTab(id);assert.ok(api.state().tabs.find(t=>t.id===id).pinned);assert.ok(api.state().tabs.findIndex(t=>t.id===id)<api.state().tabs.findIndex(t=>!t.pinned));log('Pinning moves the tab into the group at the top');
    await until(()=>!!t.favicon);await until(()=>win.webContents.executeJavaScript('!!document.querySelector("#pinned-tabs .site-icon img")'));assert.match(t.favicon,/^data:image\/png;base64,/);log('Website favicon is decoded to a small PNG and displayed in the pinned button');
    await t.view.webContents.executeJavaScript('(async()=>{const canvas=document.createElement("canvas");canvas.width=640;canvas.height=360;const ctx=canvas.getContext("2d");ctx.fillStyle="#121212";ctx.fillRect(0,0,640,360);ctx.fillStyle="#eeeeee";ctx.font="24px sans-serif";ctx.fillText("Kernel fullscreen test",160,180);const v=document.createElement("video");v.id="test-video";v.muted=true;v.srcObject=canvas.captureStream(1);document.body.append(v);await v.play();await v.requestFullscreen();return true;})()',true);
    await until(()=>api.state().contentFullscreen);await until(()=>win.isFullScreen());await delay(500);
    const fullscreenBounds=t.view.getBounds();assert.equal(fullscreenBounds.x,0);assert.equal(fullscreenBounds.y,0);assert.equal(fullscreenBounds.width,win.getContentSize()[0]);assert.equal(fullscreenBounds.height,win.getContentSize()[1]);
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.querySelector(".sidebar")).visibility'),'hidden');
    fs.writeFileSync(path.join(output,'Kernel-fullscreen-preview.png'),(await t.view.webContents.capturePage()).toPNG());
    t.view.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await until(()=>!api.state().contentFullscreen);await until(()=>!win.isFullScreen());await delay(200);assert.equal(t.view.getBounds().y,48);
    await t.view.webContents.executeJavaScript('document.getElementById("test-video").srcObject.getTracks().forEach(t=>t.stop());document.getElementById("test-video").remove()');log('Real video enters fullscreen without a permission dialog, hides all chrome, and Escape restores it');

    await t.view.webContents.executeJavaScript('document.getElementById("next").click()',true);await until(()=>t.title==='Second page');await until(()=>!t.loading);assert.ok(api.state().tabs.find(t=>t.id===id).back);await win.webContents.executeJavaScript('window.kernel.call("history:navigate","back")');await until(()=>t.title==='Kernel Test');log('Navigation and back history work');
    await t.view.webContents.executeJavaScript('document.getElementById("popup").click()');await until(()=>tabs.some(t=>t.title==='Security'));const secure=tabs.find(t=>t.title==='Security');
    assert.equal(await secure.view.webContents.executeJavaScript('document.body.dataset.node'),'undefined');assert.equal(await secure.view.webContents.executeJavaScript('document.body.dataset.bridge'),'undefined');log('Popup creates a tab; remote pages cannot access Node or privileged bridge');
    await win.webContents.executeJavaScript('window.kernel.call("panel","ai")');await delay(300);api.selectTab(id);await delay(300);
    const bounds=t.view.getBounds();assert.equal(bounds.x,232);assert.equal(bounds.width,win.getContentSize()[0]-630);log('AI panel reserves space without covering the page');
    await win.webContents.executeJavaScript('window.kernel.call("overlay",true)');await delay(200);assert.ok(!win.contentView.children.includes(t.view));await win.webContents.executeJavaScript('window.kernel.call("overlay",false)');await delay(200);assert.ok(win.contentView.children.includes(t.view));log('Settings detach the native page and restore it');
    await win.webContents.executeJavaScript('window.kernel.call("settings",{collapsed:true})');await delay(200);assert.equal(t.view.getBounds().x,72);await win.webContents.executeJavaScript('window.kernel.call("settings",{collapsed:false})');log('Compact sidebar changes the actual content bounds');
    await win.webContents.executeJavaScript('window.kernel.call("settings",{theme:"custom",background:"#20242a",surface:"#2a3038",foreground:"#f0f2f5",accent:"#9bbce6",sidebarWidth:280,panelWidth:440,showRail:false})');
    await win.webContents.executeJavaScript('window.kernel.call("panel","ai")');await delay(250);
    assert.equal(t.view.getBounds().x,280);assert.equal(t.view.getBounds().width,win.getContentSize()[0]-720);
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.body).backgroundColor'),'rgb(32, 36, 42)');
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.querySelector(".rail")).display'),'none');log('Custom palette and panel widths update the real browser layout');
    await win.webContents.executeJavaScript('window.kernel.call("overlay",true)');
    await win.webContents.executeJavaScript('document.querySelector("[data-settings-page=appearance]").click();const el=document.querySelector("[data-setting=fontFamily]");el.value="Arial";el.dispatchEvent(new Event("change"));const size=document.querySelector("[data-setting=fontSize]");size.value="15";size.dispatchEvent(new Event("change"));');
    await until(()=>api.state().settings.fontFamily==='Arial'&&api.state().settings.fontSize===15);await delay(250);
    assert.match(await win.webContents.executeJavaScript('getComputedStyle(document.body).fontFamily'),/Arial/);
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.body).fontSize'),'15px');log('Appearance controls apply fonts and text size through the UI');
    await delay(300);const appearanceSaved=JSON.parse(fs.readFileSync(path.join(api.app.getPath('userData'),'browser.json'),'utf8')).settings;assert.equal(appearanceSaved.fontFamily,'Arial');assert.equal(appearanceSaved.sidebarWidth,280);assert.equal(appearanceSaved.background,'#20242a');log('Custom appearance is saved to the profile');
    await win.webContents.executeJavaScript('window.kernel.call("settings:reset")');await delay(250);
    assert.equal(api.state().settings.fontFamily,'Segoe UI');assert.equal(api.state().settings.theme,'dark');
    fs.writeFileSync(path.join(output,'Kernel-settings-preview.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript('window.kernel.call("settings",{theme:"light"})');await delay(150);
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.body).backgroundColor'),'rgb(247, 247, 247)');
    assert.equal(await win.webContents.executeJavaScript('getComputedStyle(document.documentElement).colorScheme'),'light');
    await win.webContents.executeJavaScript('window.kernel.call("settings:reset")');await win.webContents.executeJavaScript('window.kernel.call("overlay",false)');log('Light theme and reset restore coherent colors and defaults');
    t.view.webContents.sendInputEvent({type:'keyDown',keyCode:'F',modifiers:['control']});await until(()=>api.state().findVisible);
    await win.webContents.executeJavaScript('document.getElementById("find-input").value="Париж";document.getElementById("find-input").dispatchEvent(new Event("input"))');await until(()=>win.webContents.executeJavaScript('document.getElementById("find-count").textContent==="1 / 1"'));
    await t.view.webContents.executeJavaScript('const p=document.createElement("p");p.textContent="поиск поиск поиск";document.body.append(p)');
    await win.webContents.executeJavaScript('document.getElementById("find-input").value="поиск";document.getElementById("find-input").dispatchEvent(new Event("input"))');await until(()=>win.webContents.executeJavaScript('document.getElementById("find-count").textContent==="1 / 3"'));
    await win.webContents.executeJavaScript('document.getElementById("find-next").click()');await until(()=>win.webContents.executeJavaScript('document.getElementById("find-count").textContent==="2 / 3"'));
    await win.webContents.executeJavaScript('document.getElementById("find-previous").click()');await until(()=>win.webContents.executeJavaScript('document.getElementById("find-count").textContent==="1 / 3"'));
    assert.equal(t.view.getBounds().y,84);await win.webContents.executeJavaScript('document.getElementById("find-close").click()');await until(()=>!api.state().findVisible);assert.equal(t.view.getBounds().y,48);log('Page search finds real content and reserves space above the page');
    const beforeHistory=api.state().history.length;
    await win.webContents.executeJavaScript('window.kernel.call("settings",{saveHistory:false,homepage:'+JSON.stringify(origin+'/two')+',newTab:"home",defaultZoom:125,spellcheck:false})');
    const customId=await win.webContents.executeJavaScript('window.kernel.call("tab:new")');await until(()=>tabs.find(x=>x.id===customId)?.title==='Second page');await delay(200);
    assert.equal(tabs.find(x=>x.id===customId).view.webContents.getZoomFactor(),1.25);assert.equal(api.state().history.length,beforeHistory);
    assert.equal(t.view.webContents.session.isSpellCheckerEnabled(),false);
    api.closeTab(customId);api.selectTab(id);await win.webContents.executeJavaScript('window.kernel.call("home")');await until(()=>t.title==='Second page');
    api.navigate(origin);await until(()=>t.title==='Kernel Test');await win.webContents.executeJavaScript('window.kernel.call("settings:reset")');log('Homepage, new-tab behavior, default zoom, spellchecking and disabled history work');
    const ctx=await api.pageContext();assert.ok(ctx.text.includes('Париж'));log('Page context reads text from the active tab');
    const downloadPath=path.join(api.app.getPath('userData'),'kernel-test.txt');
    t.view.webContents.session.once('will-download',(_e,item)=>item.setSavePath(downloadPath));
    t.view.webContents.downloadURL(origin+'/file');await until(()=>api.state().downloads.some(d=>d.status==='completed'));assert.equal(fs.readFileSync(downloadPath,'utf8'),'Kernel download works');log('Native file download completes and appears in the downloads panel');
    const downloadFolder=path.join(api.app.getPath('userData'),'automatic-downloads');fs.mkdirSync(downloadFolder,{recursive:true});
    await win.webContents.executeJavaScript('window.kernel.call("settings",{askDownload:false,downloadDirectory:'+JSON.stringify(downloadFolder)+'})');
    t.view.webContents.downloadURL(origin+'/file');await until(()=>fs.existsSync(path.join(downloadFolder,'kernel-test.txt'))&&api.state().downloads.filter(d=>d.status==='completed').length===2);
    t.view.webContents.downloadURL(origin+'/file');await until(()=>fs.existsSync(path.join(downloadFolder,'kernel-test (1).txt'))&&api.state().downloads.filter(d=>d.status==='completed').length===3);
    await win.webContents.executeJavaScript('window.kernel.call("settings:reset")');log('Automatic downloads use the configured folder and preserve existing filenames');
    await win.webContents.executeJavaScript('window.kernel.call("panel","ai")');
    await win.webContents.executeJavaScript('window.kernel.call("bookmark")');await delay(400);
    const persisted=JSON.parse(fs.readFileSync(path.join(api.app.getPath('userData'),'browser.json'),'utf8'));assert.ok(persisted.tabs.some(t=>t.pinned&&t.url===origin+'/'));assert.ok(persisted.bookmarks.some(b=>b.url===origin+'/'));assert.ok(persisted.history.some(h=>h.url===origin+'/'));log('Session, pinned tabs, bookmarks and history are written to disk');
    await t.view.webContents.executeJavaScript('localStorage.setItem("test-site-data","present");document.cookie="test=present"');
    await win.webContents.executeJavaScript('localStorage.setItem("test-ui-data","preserved");window.kernel.call("overlay",true)');await delay(150);
    await win.webContents.executeJavaScript('document.querySelector("[data-settings-page=privacy]").click();document.getElementById("open-clear-data").click();document.getElementById("clear-sites").checked=true;document.getElementById("clear-visits").checked=true;document.getElementById("confirm-clear-data").click();');
    await until(()=>win.webContents.executeJavaScript('!document.getElementById("clear-data-dialog").open'));
    assert.equal(await t.view.webContents.executeJavaScript('localStorage.getItem("test-site-data")'),null);assert.equal(await t.view.webContents.executeJavaScript('document.cookie'),'');assert.equal(api.state().history.length,0);
    assert.equal(await win.webContents.executeJavaScript('localStorage.getItem("test-ui-data")'),'preserved');log('Selected data is cleared from websites without deleting chat or interface storage');
    await win.webContents.executeJavaScript('window.kernel.call("overlay",false)');
    const internetId=api.createTab('https://example.com');await until(()=>tabs.find(t=>t.id===internetId)?.title==='Example Domain',30000);assert.equal(tabs.find(t=>t.id===internetId).error,'');log('External HTTPS website opens with TLS checks enabled');api.closeTab(internetId);api.selectTab(id);
    const info=api.bypass.info();assert.equal(info.version,'1.10.3');assert.ok(info.profiles.length>=10);assert.equal(info.phase,'off');log('Bundled bypass strategies load; no system networking was changed by tests');
    if(assistant.info().installed){
      const tokens=[];const original=assistant.emit;assistant.emit=(channel,data)=>{if(channel==='ai-token')tokens.push(data);original(channel,data);};
      const result=await assistant.chat({messages:[{role:'user',content:'Ответь одним коротким предложением по-русски: чему равно 2 + 2?'}],context:false});assert.ok(result.text.includes('4')||result.text.toLowerCase().includes('четыр'));assert.ok(tokens.length>0);log('Bundled Qwen3-4B returns a real streamed answer: '+result.text.trim());
      assert.equal(assistant.backend,'Vulkan · GPU');assert.ok(assistant.metrics?.tokensPerSecond>0);log('Automatic backend uses the available GPU and reports actual inference timings');
      const answer=await assistant.chat({messages:[{role:'user',content:'Какая столица Франции указана на текущей странице? Ответь одним словом.'}],context:true});assert.match(answer.text,/Париж/i);log('Assistant answers from the active page context');
      const actionEvents=[];assistant.emit=(channel,data)=>{if(channel==='ai-action')actionEvents.push(data);original(channel,data);};
      await assistant.chat({messages:[{role:'user',content:'Используй функцию open_tab и предложи открыть https://github.com с заголовком GitHub.'}],context:false});assert.ok(actionEvents.some(a=>a.url==='https://github.com/'));log('Agent proposes a real browser action for user confirmation');
      assistant.emit=original;
      const unauthorized=await fetch('http://127.0.0.1:'+assistant.port+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:'Hi'}]})});assert.equal(unauthorized.status,401);log('Local inference API rejects requests without the private key');
      await win.webContents.executeJavaScript('document.getElementById("chat-input").value="Напиши подробный рассказ на тысячу слов.";document.getElementById("chat-form").requestSubmit()');
      await until(()=>win.webContents.executeJavaScript('!document.getElementById("stop-message").classList.contains("hidden")'));await delay(400);await win.webContents.executeJavaScript('document.getElementById("stop-message").click()');
      await until(()=>win.webContents.executeJavaScript('document.getElementById("stop-message").classList.contains("hidden")'));log('Stop button cancels the running inference request');
      await win.webContents.executeJavaScript('document.querySelector("[data-action=clear-chat]").click()');
      await win.webContents.executeJavaScript('document.getElementById("chat-input").value="Скажи коротко: браузер готов.";document.getElementById("chat-form").requestSubmit()');
      await until(()=>win.webContents.executeJavaScript('document.querySelectorAll(".chat-message.assistant .message-content").length>0 && document.querySelector("#stop-message").classList.contains("hidden")'),180000);log('Chat composer sends and renders a local model response through IPC');
    }else log('Model not installed: local AI inference skipped');
    const homeId=api.createTab();for(const tab of [...tabs])if(tab.id!==homeId)api.closeTab(tab.id);
    api.createTab('https://www.youtube.com/',{title:'YouTube',pinned:true,activate:false});api.createTab('https://github.com/',{title:'GitHub',pinned:true,activate:false});api.selectTab(homeId);
    await win.webContents.executeJavaScript('window.kernel.call("bookmark:remove",'+JSON.stringify(origin+'/')+')');
    await win.webContents.executeJavaScript('window.kernel.call("overlay",true)');await delay(200);
    await win.webContents.executeJavaScript('document.querySelector("[data-settings-page=appearance]").click();document.getElementById("content").scrollTop=0;document.getElementById("toast").classList.add("hidden")');
    fs.writeFileSync(path.join(output,'Kernel-settings-preview.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript('window.kernel.call("overlay",false)');
    await win.webContents.executeJavaScript('window.kernel.call("panel","ai")');await delay(500);fs.writeFileSync(path.join(output,'Kernel-Chat-preview.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript('window.kernel.call("panel","")');
    assert.deepEqual(errors,[]);log('No renderer console errors');
    fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({ok:true,checks:report,at:new Date().toISOString(),versions:process.versions},null,2));console.log('SMOKE TEST OK');
  }catch(e){console.error(e);fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({ok:false,checks:report,error:e.stack},null,2));api.app.exitCode=1;}
  finally{assistant.stop();if(server)server.close();api.app.exit(api.app.exitCode||0);}
};
