const test=require('node:test'),assert=require('node:assert/strict'),net=require('node:net'),http=require('node:http');const {ProxyProvider}=require('../src/connection/providers.cjs');
test('SOCKS5 authenticates, resolves destination remotely and carries HTTP and CONNECT traffic',{timeout:15000},async()=>{
 const sockets=new Set(),destinations=[];const origin=http.createServer((req,res)=>res.end('SOCKS result'));await new Promise(r=>origin.listen(0,'127.0.0.1',r));
 const socks=net.createServer(socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.on('error',()=>{});let buffer=Buffer.alloc(0),stage=0;const read=chunk=>{buffer=Buffer.concat([buffer,chunk]);if(stage===0&&buffer.length>=2+buffer[1]){buffer=buffer.subarray(2+buffer[1]);stage=1;socket.write(Buffer.from([5]));setImmediate(()=>socket.write(Buffer.from([2])));}if(stage===1&&buffer.length>=3){const u=buffer[1];if(buffer.length<3+u+buffer[2+u])return;const p=buffer[2+u];assert.equal(buffer.subarray(2,2+u).toString(),'user');assert.equal(buffer.subarray(3+u,3+u+p).toString(),'secret');buffer=buffer.subarray(3+u+p);stage=2;socket.write(Buffer.from([1,0]));}if(stage===2&&buffer.length>=5){assert.equal(buffer[3],3);const n=buffer[4];if(buffer.length<7+n)return;const host=buffer.subarray(5,5+n).toString(),port=buffer.readUInt16BE(5+n);destinations.push(host);buffer=buffer.subarray(7+n);stage=3;socket.removeListener('data',read);const remote=net.connect(port,'127.0.0.1',()=>{socket.write(Buffer.from([5,0,0]));setImmediate(()=>{socket.write(Buffer.from([1,127,0,0,1,0,0]));if(buffer.length)remote.write(buffer);socket.pipe(remote);remote.pipe(socket);});});sockets.add(remote);remote.on('close',()=>sockets.delete(remote));remote.on('error',()=>socket.destroy());socket.on('close',()=>remote.destroy());}};socket.on('data',read);});await new Promise(r=>socks.listen(0,'127.0.0.1',r));const provider=new ProxyProvider({type:'socks5',host:'127.0.0.1',port:socks.address().port},{username:'user',password:'secret'});
 try{const [port,sharedPort]=await Promise.all([provider.start(),provider.start()]);assert.equal(port,sharedPort);const text=await new Promise((resolve,reject)=>http.get({hostname:'127.0.0.1',port,path:'http://remote-only.test:'+origin.address().port+'/resource',timeout:5000},res=>{let text='';res.on('data',d=>text+=d);res.on('end',()=>resolve(text));}).on('timeout',function(){this.destroy(Error('HTTP timeout'));}).on('error',reject));assert.equal(text,'SOCKS result');
 const body=await new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,method:'CONNECT',path:'remote-only.test:'+origin.address().port,timeout:5000});req.on('connect',(res,socket)=>{assert.equal(res.statusCode,200);let data='';socket.on('data',d=>data+=d);socket.on('end',()=>resolve(data));socket.on('error',reject);socket.write('GET / HTTP/1.1\r\nHost: remote-only.test\r\nConnection: close\r\n\r\n');});req.on('error',reject);req.on('timeout',()=>req.destroy(Error('CONNECT timeout')));req.end();});assert.match(body,/SOCKS result/);assert.deepEqual(destinations,['remote-only.test','remote-only.test']);
 }finally{provider.stop();for(const s of sockets)s.destroy();origin.closeAllConnections();await Promise.all([new Promise(r=>origin.close(r)),new Promise(r=>socks.close(r))]);}
});

