const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {atomicWrite,readJSON}=require('../core.cjs');const {MODES,hostOf,resolvePolicy,profileFor,failover,validateProxy}=require('./policy.cjs');const {ProxyProvider,TorProvider}=require('./providers.cjs');
class ConnectionManager{
  constructor({root,basePartition,session,vault,vendor,changed,setup}){Object.assign(this,{root,basePartition,session,vault,vendor,changed,setup});this.file=path.join(root,'connection.json');const data=readJSON(this.file,{});this.profiles=[{id:'tor',name:'Tor · автоматический',type:'tor',region:'Автоматически',transport:'direct'},{id:'tor-snowflake',name:'Tor · Snowflake',type:'tor',region:'Автоматически',transport:'snowflake'},...(data.profiles||[]).filter(p=>/^[a-f\d-]{36}$/i.test(p.id)&&['http','https','socks5'].includes(p.type)).slice(0,30)];this.sites=data.sites||{};this.global=data.global||{mode:'direct'};this.workspace=data.workspace||null;this.options={killSwitch:true,autoFallback:true,reconnect:true,...data.options};this.tabs=new Map();this.tabURLs=new Map();this.contexts=new Map();this.providers=new Map();this.tabStates=new Map();this.timer=setInterval(()=>this.health(),45000);this.timer.unref();}
  save(){atomicWrite(this.file,{profiles:this.profiles.filter(p=>p.type!=='tor'),sites:this.sites,global:this.global,workspace:this.workspace,options:this.options});}
  secret(profile){try{return JSON.parse(this.vault.decryptString(Buffer.from(profile.secret,'base64')));}catch{return{};}}
  saveProxy(input){const p=validateProxy(input);let existing=this.profiles.find(p=>p.id===input.id);const id=existing?.id||crypto.randomUUID();if(input.username!==undefined||input.password!==undefined){if(!this.vault.isEncryptionAvailable())throw Error('Защищённое хранилище Windows недоступно.');p.secret=this.vault.encryptString(JSON.stringify({username:String(input.username||'').slice(0,255),password:String(input.password||'').slice(0,255)})).toString('base64');}else p.secret=existing?.secret;this.profiles=this.profiles.filter(p=>p.id!==id);this.profiles.push({...p,id});this.providers.get(id)?.stop();this.providers.delete(id);const ctx=this.contexts.get(id);if(ctx){ctx.ready=null;ctx.generation=(ctx.generation||0)+1;}this.save();this.changed();return id;}
  removeProfile(id){if(id.startsWith('tor'))throw Error('Встроенный профиль нельзя удалить.');this.profiles=this.profiles.filter(p=>p.id!==id);this.providers.get(id)?.stop();this.providers.delete(id);this.prune();this.save();this.changed();}
  assign({tabId,url,mode,profileId,scope='tab',enabled=true}){if(!MODES.includes(mode)||!['tab','site','workspace','all'].includes(scope))throw Error('Неверный маршрут.');const route={mode,profileId:String(profileId||'').slice(0,64),enabled:!!enabled};if(scope==='site'){const host=hostOf(url);if(!host)throw Error('Откройте сайт.');this.sites[host]=route;this.tabs.delete(tabId);}else if(scope==='workspace'){this.workspace=route;this.tabs.delete(tabId);}else if(scope==='all'){this.global=route;this.tabs.clear();}else this.tabs.set(tabId,route);this.prune();this.save();this.changed();}
  prune(){const used=new Set([...this.tabURLs].map(([id,url])=>this.key(id,url)));for(const [id,p]of this.providers)if(!used.has(id)){p.stop();this.providers.delete(id);const ctx=this.contexts.get(id);if(ctx){ctx.ready=null;ctx.generation=(ctx.generation||0)+1;}}}
  policy(tabId,url){return resolvePolicy({tab:this.tabs.get(tabId),url,workspace:this.workspace,global:this.global,sites:this.sites});}
  key(tabId,url){const r=this.policy(tabId,url);if(r.mode==='direct')return 'direct';return profileFor(r,this.profiles)?.id||'blocked-'+r.mode;}
  partitionFor(tabId,url){const key=this.key(tabId,url);return key==='direct'?this.basePartition:this.basePartition+'-route-'+key;}
  state(tabId,url){const route=this.policy(tabId,url),profile=profileFor(route,this.profiles),provider=profile&&this.providers.get(profile.id),s=this.tabStates.get(tabId);return{mode:this.tabs.get(tabId)?.mode==='smart'?'smart':route.mode,effectiveMode:route.mode,profileId:profile?.id||'',profileName:profile?.name||'',state:route.mode==='direct'?'connected':s?.state||provider?.status||'disconnected',progress:provider?.progress||0,latency:s?.latency||provider?.latency||null,error:s?.error||'',dns:route.mode==='direct'?'Настройки браузера':'Через маршрут',webrtc:route.mode==='direct'?'Обычная политика':'UDP вне прокси запрещён'};}
  info(tabId,url){return{...this.state(tabId,url),profiles:this.profiles.map(({secret,...p})=>({...p,hasCredentials:!!secret})),sites:this.sites,global:this.global,options:this.options};}
  async prepare(tabId,url,attempted=new Set()){if(this.stopping)throw Error('Браузер закрывается.');const route=this.policy(tabId,url),key=this.key(tabId,url),ses=this.session.fromPartition(this.partitionFor(tabId,url));attempted.add(key);this.tabURLs.set(tabId,url);this.setup(ses);if(key==='direct')return ses;let ctx=this.contexts.get(key);if(!ctx){ctx={session:ses};this.contexts.set(key,ctx);ctx.init=ses.setProxy({mode:'fixed_servers',proxyRules:'http=127.0.0.1:1;https=127.0.0.1:1',proxyBypassRules:'<-loopback>'});}if(ctx.ready){await ctx.ready;this.tabStates.set(tabId,{state:'connected'});return ses;}const generation=ctx.generation||0,profile=profileFor(route,this.profiles);this.tabStates.set(tabId,{state:'connecting'});this.changed();
    ctx.ready=(async()=>{await ctx.init;if(!profile)throw Error('Добавьте прокси в Connection.');let provider=this.providers.get(key);if(!provider){provider=profile.type==='tor'?new TorProvider({vendor:this.vendor,root:this.root,profile,changed:this.changed}):new ProxyProvider(profile,this.secret(profile));this.providers.set(key,provider);}const port=await provider.start();await ses.setProxy({mode:'fixed_servers',proxyRules:(profile.type==='tor'?'socks5':'http')+'://127.0.0.1:'+port,proxyBypassRules:'<-loopback>'});await ses.closeAllConnections();this.tabStates.set(tabId,{state:'connected'});this.changed();return ses;})();
    try{await ctx.ready;}catch(e){if(this.stopping||this.key(tabId,url)!==key||(ctx.generation||0)!==generation)throw Error('Маршрут изменён.');ctx.ready=null;this.tabStates.set(tabId,{state:'failed',error:e.message});this.changed();const next=failover(route,this.profiles.filter(p=>!attempted.has(p.id)),key,this.options.autoFallback);if(next){this.tabs.set(tabId,{...route,profileId:next.id});this.tabStates.set(tabId,{state:'reconnecting'});return this.prepare(tabId,url,attempted);}if(!this.options.killSwitch){this.tabs.set(tabId,{mode:'direct'});return this.prepare(tabId,url,attempted);}throw e;}return ses;
  }
  requestFailed(tabId){const s=this.tabStates.get(tabId);if(s){s.state='degraded';this.changed();}}
  async diagnose(tabId,url){const ses=await this.prepare(tabId,url),start=Date.now();const r=await ses.fetch('https://check.torproject.org/api/ip',{signal:AbortSignal.timeout(30000),cache:'no-store'});if(!r.ok)throw Error('Проверка IP недоступна.');const result=await r.json(),latency=Date.now()-start;this.tabStates.set(tabId,{state:'connected',latency});this.changed();return{ip:result.IP,isTor:!!result.IsTor,latency,dns:this.state(tabId,url).dns,webrtc:this.state(tabId,url).webrtc};}
  health(){if(this.stopping)return;for(const [id,p]of this.providers)if(p instanceof TorProvider&&p.status==='failed'){const ctx=this.contexts.get(id);if(ctx)ctx.ready=null;for(const [tabId,url]of this.tabURLs)if(this.key(tabId,url)===id){this.tabStates.set(tabId,{state:'failed',error:'Соединение Tor прервано.'});if(this.options.reconnect)this.prepare(tabId,url).then(()=>this.recovered?.(tabId)).catch(()=>{});}this.changed();}}
  dispose(){this.stopping=true;clearInterval(this.timer);for(const p of this.providers.values())p.stop();}
}
module.exports={ConnectionManager};
