const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),http=require('node:http'),https=require('node:https'),{spawn}=require('node:child_process');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const connect=(host,port)=>new Promise((resolve,reject)=>{const s=net.connect({host,port});s.setTimeout(12000,()=>s.destroy(Error('Маршрут не отвечает.')));s.once('error',reject);s.once('connect',()=>{s.setTimeout(0);resolve(s);});});
async function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});}
async function socksConnect(profile,secret,host,port){
  const s=await connect(profile.host,profile.port);let buffer=Buffer.alloc(0),waiting;const data=d=>{buffer=Buffer.concat([buffer,d]);waiting?.();};s.on('data',data);const read=async n=>{const end=Date.now()+12000;while(buffer.length<n){if(s.destroyed)throw Error('Прокси закрыл соединение.');if(Date.now()>end)throw Error('Прокси не отвечает.');await new Promise(r=>{waiting=r;setTimeout(r,100);});}const b=buffer.subarray(0,n);buffer=buffer.subarray(n);return b;};
  try{s.write(Buffer.from(secret.username?[5,2,0,2]:[5,1,0]));const hello=await read(2);if(hello[0]!==5||hello[1]===255)throw Error('Прокси отклонил подключение.');if(hello[1]===2){const u=Buffer.from(secret.username||''),p=Buffer.from(secret.password||'');if(u.length>255||p.length>255)throw Error('Учётные данные слишком длинные.');s.write(Buffer.concat([Buffer.from([1,u.length]),u,Buffer.from([p.length]),p]));if((await read(2))[1]!==0)throw Error('Прокси отклонил учётные данные.');}else if(hello[1]!==0)throw Error('Метод SOCKS5 не поддерживается.');const h=Buffer.from(host);if(h.length>255)throw Error('Неверный адрес назначения.');s.write(Buffer.concat([Buffer.from([5,1,0,3,h.length]),h,Buffer.from([port>>8,port&255])]));const reply=await read(4);if(reply[1]!==0)throw Error('SOCKS5 не смог открыть сайт.');if(reply[3]===1)await read(6);else if(reply[3]===4)await read(18);else if(reply[3]===3){const size=(await read(1))[0];await read(size+2);}else throw Error('Неверный ответ SOCKS5.');s.pause();s.removeListener('data',data);if(buffer.length)s.unshift(buffer);return s;}catch(e){s.destroy();throw e;}
}
class ProxyProvider{
  constructor(profile,secret={}){Object.assign(this,{profile,secret});this.sockets=new Set();}
  async start(){if(this.server&&this.port)return this.port;if(this.starting)return this.starting;this.starting=this.open().finally(()=>{this.starting=null;});return this.starting;}
  async open(){const generation=this.generation||0;const p=this.profile,secret=this.secret;const started=Date.now(),probe=await connect(p.host,p.port);probe.destroy();if((this.generation||0)!==generation)throw Error('Маршрут изменён.');this.latency=Date.now()-started;const track=s=>{this.sockets.add(s);s.on('close',()=>this.sockets.delete(s));s.on('error',()=>{});return s;};const upstream=p.type==='https'?https:http;
    const authorization=secret.username?'Basic '+Buffer.from(secret.username+':'+(secret.password||'')).toString('base64'):null;
    this.server=http.createServer(async(req,res)=>{try{const target=new URL(req.url);if(!['http:','https:'].includes(target.protocol))throw Error('Unsupported destination');const headers={...req.headers};delete headers['proxy-authorization'];delete headers['proxy-connection'];let options;if(p.type==='socks5'){const socket=track(await socksConnect(p,secret,target.hostname,Number(target.port)||80));const agent=new http.Agent({keepAlive:false});agent.createConnection=()=>socket;options={hostname:target.hostname,port:Number(target.port)||80,path:target.pathname+target.search,method:req.method,headers,agent};}else{if(authorization)headers['Proxy-Authorization']=authorization;options={hostname:p.host,port:p.port,path:target.href,method:req.method,headers,agent:false};}const request=(p.type==='socks5'?http:upstream).request(options,response=>{res.writeHead(response.statusCode,response.headers);response.pipe(res);});request.on('socket',socket=>socket.resume());request.on('error',()=>{res.writeHead(502);res.end('Route unavailable');});req.pipe(request);}catch{res.writeHead(502);res.end('Route unavailable');}});
    this.server.on('connection',track);this.server.on('connect',async(req,client,head)=>{track(client);try{const target=new URL('http://'+req.url);let remote;if(p.type==='socks5')remote=await socksConnect(p,secret,target.hostname,Number(target.port)||443);else remote=await new Promise((resolve,reject)=>{const headers={Host:req.url};if(authorization)headers['Proxy-Authorization']=authorization;const r=upstream.request({hostname:p.host,port:p.port,method:'CONNECT',path:req.url,headers,agent:false,timeout:12000});r.on('connect',(response,socket,extra)=>{if(response.statusCode!==200){socket.destroy();reject(Error('Proxy rejected'));}else{if(extra.length)socket.unshift(extra);resolve(socket);}});r.on('error',reject);r.on('timeout',()=>r.destroy(Error('Timeout')));r.end();});track(remote);client.write('HTTP/1.1 200 Connection Established\r\n\r\n');if(head.length)remote.write(head);client.pipe(remote);remote.pipe(client);remote.resume();client.on('close',()=>remote.destroy());remote.on('close',()=>client.destroy());}catch{client.end('HTTP/1.1 502 Bad Gateway\r\n\r\n');}});
    await new Promise((resolve,reject)=>{this.server.once('error',reject);this.server.listen(0,'127.0.0.1',resolve);});return this.port=this.server.address().port;
  }
  stop(){this.generation=(this.generation||0)+1;for(const s of this.sockets)s.destroy();this.server?.close();this.server=null;}
}
class TorProvider{
  constructor({vendor,root,profile,changed}){Object.assign(this,{vendor,root,profile,changed});this.status='disconnected';this.progress=0;}
  async start(){if(this.status==='connected'&&this.child)return this.port;if(this.starting)return this.starting;this.starting=this.boot().finally(()=>{this.starting=null;});return this.starting;}
  update(status,progress=this.progress){this.status=status;this.progress=progress;this.changed();}
  async boot(){const generation=this.generation||0;const bundle=path.join(this.vendor,'tor'),exe=path.join(bundle,'tor','tor.exe');if(!fs.existsSync(exe))throw Error('Движок Tor не найден.');this.port=await freePort();if((this.generation||0)!==generation)throw Error('Маршрут изменён.');const directory=path.join(this.root,'connection','tor-'+this.profile.id);fs.mkdirSync(directory,{recursive:true});this.update('connecting',0);
    const args=['--ignore-missing-torrc','-f',path.join(directory,'torrc'),'--DataDirectory',directory,'--SocksPort','127.0.0.1:'+this.port,'--ClientOnly','1','--AvoidDiskWrites','1','--Log','notice stdout','--GeoIPFile',path.join(bundle,'data','geoip'),'--GeoIPv6File',path.join(bundle,'data','geoip6')];
    if(this.profile.transport==='snowflake'){const pt=path.join(bundle,'tor','pluggable_transports'),config=JSON.parse(fs.readFileSync(path.join(pt,'pt_config.json')));const bridge=config.bridges?.snowflake?.[0];if(!bridge)throw Error('Snowflake не настроен в комплекте Tor.');args.push('--UseBridges','1','--ClientTransportPlugin','snowflake exec ./lyrebird.exe','--Bridge',bridge);}
    const child=this.child=spawn(exe,args,{cwd:path.join(bundle,'tor','pluggable_transports'),windowsHide:true,stdio:['ignore','pipe','pipe']});let pending='';child.stdout.on('data',d=>{pending+=d;let i;while((i=pending.indexOf('\n'))>=0){const line=pending.slice(0,i);pending=pending.slice(i+1);const m=/Bootstrapped (\d+)%/.exec(line);if(m)this.update(Number(m[1])===100?'connected':'connecting',Number(m[1]));}});child.stderr.on('data',()=>{});child.on('error',()=>{if(this.child===child){this.child=null;this.update('failed');}});child.on('exit',()=>{if(this.child===child){this.child=null;this.update('failed');}});
    const end=Date.now()+(this.profile.transport==='snowflake'?360000:180000);while(this.child===child&&Date.now()<end){if(this.status==='connected')return this.port;await delay(250);}if((this.generation||0)!==generation)throw Error('Маршрут изменён.');this.stop();this.update('failed');throw Error('Tor не смог подключиться. Попробуйте профиль Snowflake или другой маршрут.');
  }
  stop(){this.generation=(this.generation||0)+1;const child=this.child;this.child=null;child?.kill();this.update('disconnected',0);}
}
module.exports={ProxyProvider,TorProvider,socksConnect};


