const COMMANDS=[['tabs','Вкладки'],['history','История'],['bookmarks','Закладки'],['settings','Настройки'],['workspace','Workspaces'],['ai','Спросить ИИ'],['privacy','Приватность сайта'],['performance','Производительность'],['translate','Перевести страницу'],['summarize','Краткое содержание'],['notes','Заметки'],['capsules','Page Capsule'],['security','Безопасность сайта'],['ghost','Ghost Mode']].map(([id,title])=>({id,title}));
function calculate(value){
  if(!/^[\d\s.+\-*/%^()]+$/.test(value)||value.length>150||!/[+*/%^()-]/.test(value))return null;
  const tokens=value.match(/(?:\d+(?:\.\d*)?|\.\d+)|[+\-*/%^()]/g)||[];let i=0;
  const expression=(minimum=0)=>{let left;const token=tokens[i++];if(token==='+'||token==='-')left=(token==='-'?-1:1)*expression(4);else if(token==='('){left=expression();if(tokens[i++]!==')')throw Error();}else{left=Number(token);if(token===undefined||!Number.isFinite(left))throw Error();}while(i<tokens.length){const op=tokens[i],precedence={'+':1,'-':1,'*':2,'/':2,'%':2,'^':3}[op];if(!precedence||precedence<minimum)break;i++;const right=expression(precedence+(op==='^'?0:1));left=op==='+'?left+right:op==='-'?left-right:op==='*'?left*right:op==='/'?left/right:op==='%'?left%right:left**right;if(!Number.isFinite(left))throw Error();}return left;};
  try{const result=expression();return i===tokens.length?Number(result.toPrecision(12)):null;}catch{return null;}
}
function intent(input){const value=String(input||'').trim().slice(0,8192);const slash=/^\/(\w+)(?:\s+(.*))?$/.exec(value),legacy=/^(tabs|history|bookmarks):\s*(.*)$/i.exec(value);if(slash&&COMMANDS.some(c=>c.id===slash[1].toLowerCase()))return{kind:'command',command:slash[1].toLowerCase(),query:slash[2]||''};if(legacy)return{kind:'command',command:legacy[1].toLowerCase(),query:legacy[2]};if(/^(?:internal|kernel)\s+(?:settings|настройки)$/i.test(value))return{kind:'command',command:'settings',query:''};const result=calculate(value);if(result!==null)return{kind:'calculator',value:result};return{kind:'navigate',value};}
function suggestions(input,{tabs=[],history=[],bookmarks=[],settings=[],commands=[],workspaces=[]}={}){
  const parsed=intent(input),q=(parsed.kind==='command'?parsed.query:String(input||'')).toLowerCase(),rows=[];
  if(parsed.kind==='calculator')rows.push({type:'calculator',title:String(parsed.value),hint:'Копировать результат',value:String(parsed.value)});
  if(String(input).startsWith('/')&&!String(input).includes(' '))for(const c of COMMANDS.filter(c=>('/'+c.id).includes(String(input).toLowerCase())))rows.push({type:'command',command:c.id,title:'/'+c.id,hint:c.title});
  const types=parsed.kind==='command'?[parsed.command]:['tabs','bookmarks','history','settings','workspace'];
  for(const type of types){const list={tabs,history,bookmarks,settings,workspace:workspaces}[type]||[];for(const item of list){if((item.title+' '+(item.name||'')+' '+(item.url||'')+' '+(item.hint||'')).toLowerCase().includes(q))rows.push({type,id:item.id,title:item.title||item.name,url:item.url,hint:item.hint||type,section:item.section});if(rows.length>=24)break;}}
  if(parsed.kind!=='command'&&q)for(const c of commands.filter(c=>(c.title+' '+c.hint).toLowerCase().includes(q)).slice(0,4))rows.push({type:'tool',id:c.id,title:c.title,hint:c.group});
  if(parsed.kind==='navigate'&&parsed.value)rows.unshift({type:'navigate',value:parsed.value,title:parsed.value,hint:'Открыть адрес или найти в интернете'});
  if(parsed.kind==='command'&&!['tabs','history','bookmarks','workspace','settings'].includes(parsed.command))rows.unshift({type:'command',command:parsed.command,query:parsed.query,title:'/'+parsed.command+' '+parsed.query,hint:COMMANDS.find(c=>c.id===parsed.command)?.title});
  return rows.slice(0,24);
}
const TRACKERS=['doubleclick.net','google-analytics.com','googletagmanager.com','connect.facebook.net','facebook.com/tr','hotjar.com','hotjar.io','segment.io','segment.com','clarity.ms','scorecardresearch.com'];
function trackerHost(url){try{const u=new URL(url);return TRACKERS.find(rule=>{const [domain,...parts]=rule.split('/');return (u.hostname===domain||u.hostname.endsWith('.'+domain))&&(!parts.length||u.pathname.startsWith('/'+parts.join('/')));})||null;}catch{return null;}}
function securitySummary({url,headers={},cookies=[],redirects=[],mixed=[],tls=null}={}){const h=Object.fromEntries(Object.entries(headers).map(([k,v])=>[k.toLowerCase(),Array.isArray(v)?v.join('\n'):String(v)]));return{https:String(url).startsWith('https:'),tls,headers:Object.fromEntries(['content-security-policy','strict-transport-security','x-content-type-options','x-frame-options','referrer-policy','permissions-policy','cross-origin-opener-policy','cross-origin-resource-policy'].map(k=>[k,h[k]||'Не указан'])),cookies:cookies.map(c=>({name:c.name,domain:c.domain,secure:c.secure,httpOnly:c.httpOnly,sameSite:c.sameSite})),redirects,mixedContent:mixed,limitations:'Пассивные наблюдения этого запуска. Отсутствие заголовка само по себе не доказывает уязвимость.'};}
module.exports={COMMANDS,intent,suggestions,calculate,trackerHost,securitySummary};
