const {trackerHost,securitySummary}=require('./commands.cjs');
function liveContents(tab){const wc=tab?.view?.webContents;return wc&&!wc.isDestroyed?.()?wc:null;}
class Diagnostics{
  constructor({tabs,settings}){Object.assign(this,{tabs,settings});this.sites=new Map();this.sessions=new WeakSet();}
  record(id){if(!this.sites.has(id))this.sites.set(id,{requests:0,trackers:0,blocked:0,hosts:new Set(),headers:{},mixed:new Set()});return this.sites.get(id);}
  requestTab(id){if(!Number.isInteger(id)||id<=0)return;return this.tabs.find(t=>liveContents(t)?.id===id);}
  attach(ses){if(this.sessions.has(ses))return;this.sessions.add(ses);
    ses.webRequest.onBeforeRequest((d,callback)=>{const tab=this.requestTab(d.webContentsId);if(!tab){callback({});return;}const r=this.record(tab.id),tracker=trackerHost(d.url),s=this.settings();r.requests++;if(tracker){r.trackers++;r.hosts.add(new URL(d.url).hostname);}if(tab.url.startsWith('https:')&&d.url.startsWith('http:')&&d.resourceType!=='mainFrame')r.mixed.add(new URL(d.url).origin);let origin;try{origin=new URL(tab.url).origin;}catch{}const block=d.resourceType!=='mainFrame'&&tracker&&(s.siteTrackerBlocking?.[origin]??s.trackerBlocking);if(block)r.blocked++;callback({cancel:!!block});});
    ses.webRequest.onHeadersReceived((d,callback)=>{const tab=this.requestTab(d.webContentsId);if(tab&&d.resourceType==='mainFrame'){const r=this.record(tab.id);r.headers=Object.fromEntries(Object.entries(d.responseHeaders||{}).filter(([k])=>/^(content-security-policy|strict-transport-security|x-content-type-options|x-frame-options|referrer-policy|permissions-policy|cross-origin-opener-policy|cross-origin-resource-policy)$/i.test(k)));r.status=d.statusCode;}callback({});});
  }
  async site(tab,settings,connection,tools){const wc=liveContents(tab);if(!wc)throw Error('Сначала откройте сайт.');const url=wc.getURL();if(!/^https?:/.test(url))throw Error('Сначала откройте HTTP или HTTPS сайт.');const cookies=await wc.session.cookies.get({url}),r=this.record(tab.id),origin=new URL(url).origin;let storageEntries=null;try{storageEntries=await wc.executeJavaScript('({local:localStorage.length,session:sessionStorage.length})');}catch{}let storage=null;try{storage=await wc.executeJavaScript('navigator.storage.estimate().then(e=>({usage:e.usage,quota:e.quota})).catch(()=>null)');}catch{}const network=tools.network.get(wc.id)||[],tls=network.find(n=>n.url===url&&n.securityDetails)?.securityDetails||null;return{url,origin,requests:r.requests,trackers:r.trackers,blocked:r.blocked,trackerHosts:[...r.hosts],trackerBlocking:settings.siteTrackerBlocking?.[origin]??settings.trackerBlocking,cookieCount:cookies.length,storage,storageEntries,permissions:settings.sitePermissions[origin]||{},defaults:{media:settings.mediaPermission,geolocation:settings.locationPermission,notifications:settings.notificationPermission,'clipboard-read':settings.clipboardPermission},route:connection.info(tab.id,url),security:securitySummary({url,headers:r.headers,cookies,redirects:tab.redirects||[],mixed:[...r.mixed],tls})};}
  metrics(app,tabs,activeId){const processes=app.getAppMetrics(),byPID=new Map(processes.map(p=>[p.pid,p]));const entries=tabs.filter(Boolean).map(t=>{const wc=liveContents(t),pid=wc?wc.getOSProcessId():null,p=byPID.get(pid);return{id:t.id,title:t.title,url:t.url,pid,ramKB:p?.memory.workingSetSize||0,cpu:p?.cpu.percentCPUUsage||0,sleeping:!!t.sleeping,active:t.id===activeId,background:t.id!==activeId,audible:wc?.isCurrentlyAudible?.()||false,requests:this.sites.get(t.id)?.requests||0};});return{sampledAt:Date.now(),ramKB:processes.reduce((n,p)=>n+p.memory.workingSetSize,0),cpu:processes.reduce((n,p)=>n+p.cpu.percentCPUUsage,0),gpu:app.getGPUFeatureStatus(),gpuProcesses:processes.filter(p=>p.type==='GPU').map(p=>({pid:p.pid,ramKB:p.memory.workingSetSize,cpu:p.cpu.percentCPUUsage})),tabCount:entries.length,tabs:entries.sort((a,b)=>b.ramKB-a.ramKB),processes:processes.map(p=>({pid:p.pid,type:p.type,ramKB:p.memory.workingSetSize,cpu:p.cpu.percentCPUUsage})),note:'RAM вкладок разделяется, если Chromium использует общий процесс. Итог считается по уникальным процессам. CPU: среднее между замерами; network: наблюдаемые запросы, не скорость канала.'};}
}
module.exports={Diagnostics};
