/* Adds management tools to the existing browser chrome. Page content is always rendered as text. */
function initializeAdvanced(){
 const $=id=>document.getElementById(id),api=window.kernel;
 let state,section='tabs',generation=0,poll,searchTimer,paletteRows=[],paletteIndex=0,paletteGeneration=0,addressRows=[],addressIndex=0,addressGeneration=0,addressOverlay=false;
 const titles={tabs:'Вкладки',workspaces:'Workspaces',notes:'Заметки',capsules:'Page Capsule',privacy:'Приватность сайта',performance:'Производительность',security:'Безопасность сайта','search-history':'Поиск в истории','search-bookmarks':'Поиск закладок'};
 const aliases={'workspace':'workspaces','tab-manager':'tabs','privacy-center':'privacy','performance-center':'performance','security-center':'security','page-capsule':'capsules'};
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const guard=fn=>async(...args)=>{try{return await fn(...args);}catch(e){window.kernelUI.toast(e.message);}};
 const invoke=async(name,input={})=>{const result=await api.call('advanced',{name,input});if(!/^(info|tabs:search|notes:list|capsules:(list|open|images)|privacy:get|security:get|performance:get|search)$/.test(name))state=await api.call('state');return result;};
 const btn=(label,fn,parent,cls='tool-button')=>{const b=el('button',label,cls);b.type='button';b.onclick=guard(fn);parent.append(b);return b;};
 const field=(label,value,parent,type='text')=>{const l=el('label',label,'tool-field'),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';l.append(i);parent.append(l);return i;};
 const select=(label,options,parent,value)=>{const l=el('label',label,'tool-field'),s=el('select');for(const [v,t]of options){const o=el('option',t);o.value=v;s.append(o);}if(value!==undefined)s.value=value;l.append(s);parent.append(l);return s;};
 const check=(label,parent,value=false)=>{const l=el('label',undefined,'advanced-check'),i=el('input');i.type='checkbox';i.checked=value;l.append(i,el('span',label));parent.append(l);return i;};
 const note=(value,parent)=>parent.append(el('p',value,'tool-muted'));
 const code=(value,parent)=>parent.append(el('pre',typeof value==='string'?value:JSON.stringify(value,null,2),'tool-code'));
 const row=parent=>{const e=el('div',undefined,'advanced-row');parent.append(e);return e;};
 const heading=(title,subtitle,parent)=>{const e=el('div',undefined,'advanced-item-heading');e.append(el('strong',title),el('small',subtitle));parent.append(e);};
 const panel=el('section',undefined,'panel-section hidden');panel.id='advanced-panel';
 const header=el('header',undefined,'panel-heading'),title=el('strong','Вкладки');header.append(title);btn('×',()=>api.call('panel',''),header,'icon-button small');panel.append(header);
 const nav=el('nav',undefined,'advanced-nav');nav.setAttribute('aria-label','Центры управления');for(const [key,label]of Object.entries(titles).slice(0,7))btn(label,()=>open(key),nav);panel.append(nav);
 const content=el('div',undefined,'panel-scroll advanced-content');panel.append(content);$('side-panel').append(panel);
 const workspaceButton=el('button','Основное','workspace-switch');workspaceButton.title='Workspaces · Ctrl Shift W';workspaceButton.onclick=guard(()=>open('workspaces'));document.querySelector('.sidebar .brand').after(workspaceButton);
 const ghostBadge=el('div','Ghost · временный профиль','ghost-badge hidden');workspaceButton.after(ghostBadge);
 const more=[['tab-manager','Управление вкладками','Поиск, группы, сон, дубликаты'],['workspaces','Workspaces','Отдельные вкладки, история и настройки'],['notes','Заметки','URL, выделение и теги'],['page-capsule','Page Capsule','Офлайн библиотека страниц'],['privacy-center','Privacy Center','Трекеры, cookies, разрешения'],['performance-center','Performance Center','CPU, RAM и фоновые вкладки'],['security-center','Security Center','TLS, заголовки и риски'],['ghost','Ghost Mode','Отдельный временный профиль']];
 window.kernelCommands.push(...more.map(([id,title,hint])=>({id,title,hint,group:'Браузер'})));
 $('tools-search').dispatchEvent(new Event('input'));
 async function open(key,query=''){
  if(key==='ghost')return invoke('ghost:new');section=aliases[key]||key;if(!titles[section])return;
  await api.call('panel','advanced');state=await api.call('state');panel.classList.remove('hidden');return draw(query);
 }
 async function draw(query=''){
  const version=++generation;clearInterval(poll);content.replaceChildren();title.textContent=titles[section];nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.textContent===titles[section]));
  const local=el('div');content.append(local);const alive=()=>version===generation&&state?.panel==='advanced';
  if(section==='tabs'){
   const search=field('Поиск по названиям и содержимому',query,local,'search'),controls=row(local);
   const sort=select('Сортировка',[['recent','Недавно использованные'],['title','Название'],['domain','Домен'],['group','Группа']],local);
   sort.onchange=guard(async()=>{await invoke('tabs:sort',{by:sort.value});await list();});
   btn('По доменам',async()=>{await invoke('tabs:group-auto');await list();},controls);btn('Дубликаты',()=>window.kernelTools.run('duplicates'),controls);btn('Усыпить фоновые',async()=>{const r=await invoke('tabs:optimize');window.kernelUI.toast('Усыплено: '+r.filter(x=>x.slept).length+'. Защищённые вкладки оставлены в памяти.');await list();},controls);
   const details=el('details');details.append(el('summary','Изменить группы'));for(const g of state.advanced.groups){const n=field('Название',g.name,details),color=field('Цвет',g.color,details,'color'),actions=row(details);btn('Сохранить',async()=>{await invoke('group:update',{id:g.id,name:n.value,color:color.value});await draw();},actions);btn('Удалить группу',async()=>{await invoke('group:delete',{id:g.id});await draw();},actions);}local.append(details);const results=el('div');local.append(results);let sequence=0;
   async function list(){const token=++sequence,r=await invoke('tabs:search',{query:search.value});if(!alive()||token!==sequence)return;results.replaceChildren();note(r.note,results);
    for(const t of r.items){const item=el('article',undefined,'advanced-item');heading(t.title,t.url+(t.sleeping?' · Спит':''),item);if(t.excerpt)note(t.excerpt,item);const actions=row(item);btn('Перейти',()=>api.call('tab:select',t.id),actions);btn(t.sleeping?'Разбудить':'Усыпить',async()=>{const r=await invoke(t.sleeping?'tab:restore':'tab:sleep',{id:t.id});if(r?.reason)window.kernelUI.toast(r.reason);await list();},actions);
     const groups=state.advanced.groups||[],g=select('Группа',[['','Без группы'],...groups.map(g=>[g.id,g.name]),['new','Новая группа…']],item,t.group);g.onchange=guard(async()=>{if(g.value==='new'){const name=field('Название группы','',item);btn('Сохранить группу',async()=>{await invoke('tab:group',{id:t.id,name:name.value});await list();},item);name.focus();}else{await invoke('tab:group',{id:t.id,group:g.value});await list();}});results.append(item);}
    if(!r.items.length)note('Вкладки не найдены.',results);
   }search.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>guard(list)(),180);};await list();
  }else if(section==='workspaces'){
   note('В каждом workspace свои вкладки, группы, закладки, история и настройки. Cookies сайтов принадлежат аккаунту.',local);
   const name=field('Новый workspace','',local),icon=field('Значок','◻',local),accent=field('Цвет','#aeb6c2',local,'color');icon.maxLength=4;
   btn('Создать и переключиться',async()=>{await invoke('workspace:create',{name:name.value,icon:icon.value,accent:accent.value});await draw();},local);
   for(const w of state.advanced.workspaces){const item=el('article',undefined,'advanced-item');heading(w.icon+' '+w.name,w.count+' вкладок'+(w.id===state.advanced.workspaceId?' · Активный':''),item);const actions=row(item);if(w.id!==state.advanced.workspaceId)btn('Переключить',async()=>{await invoke('workspace:switch',{id:w.id});await open('workspaces');},actions);btn('Копия',async()=>{await invoke('workspace:duplicate',{id:w.id});await draw();},actions);
    btn('Изменить',()=>{const n=field('Название',w.name,item),i=field('Значок',w.icon,item),a=field('Цвет',w.accent,item,'color');btn('Сохранить',async()=>{await invoke('workspace:rename',{id:w.id,name:n.value,icon:i.value,accent:a.value});await draw();},item);},actions);
    if(w.id!==state.advanced.workspaceId)btn('Удалить',async()=>{await invoke('workspace:delete',{id:w.id});await draw();},actions);local.append(item);
   }btn('Снимки наборов вкладок',()=>window.kernelTools.run('workspace'),local);
  }else if(section==='notes'){
   const queryInput=field('Поиск по тексту, URL и тегам',query,local,'search'),all=check('Все workspaces',local),list=el('div');
   btn('Новая заметка к странице',()=>editNote({},local),local);local.append(list);let sequence=0;
   async function load(){const n=++sequence,items=await invoke('notes:list',{query:queryInput.value,all:all.checked});if(!alive()||n!==sequence)return;list.replaceChildren();for(const item of items){const article=el('article',undefined,'advanced-item');heading(item.text.slice(0,100)||'Заметка',new Date(item.updatedAt).toLocaleString()+' · '+item.tags.join(', '),article);note(item.url,article);btn('Открыть',()=>editNote(item,local),article);list.append(article);}if(!items.length)note('Заметок пока нет.',list);}
   queryInput.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>guard(load)(),160);};all.onchange=guard(load);await load();
  }else if(section==='capsules'){
   note('Текст, метаданные и выбранные изображения доступны без интернета. Скрипты и серверная логика не сохраняются.',local);
   const actions=row(local);btn('Сохранить страницу',()=>capsuleForm(local),actions);btn('Обычная копия сайта',()=>window.kernelTools.run('save'),actions);
   const queryInput=field('Поиск в библиотеке',query,local,'search'),list=el('div');local.append(list);let sequence=0;
   async function load(){const n=++sequence,items=await invoke('capsules:list',{query:queryInput.value});if(!alive()||n!==sequence)return;list.replaceChildren();for(const c of items){const item=el('article',undefined,'advanced-item');heading(c.title,new Date(c.at).toLocaleString(),item);note(c.url,item);btn('Читать офлайн',async()=>showCapsule(await invoke('capsules:open',{id:c.id})),item);btn('Удалить',async()=>{await invoke('capsules:delete',{id:c.id});await load();},item);list.append(item);}if(!items.length)note('Библиотека пуста.',list);}
   queryInput.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>guard(load)(),160);};await load();
  }else if(section==='privacy'||section==='security'){
   const info=await invoke(section+':get');if(!alive())return;note(info.origin,local);
   if(section==='privacy'){
    const blocking=check('Блокировать известные трекеры на этом сайте',local,info.trackerBlocking);blocking.onchange=guard(()=>invoke('privacy:block',{enabled:blocking.checked}));
    note('Запросы: '+info.requests+' · трекеры: '+info.trackers+' · заблокировано: '+info.blocked,local);note('Cookies: '+info.cookieCount+' · оценка storage: '+(info.storage?bytes(info.storage.usage):'Недоступно'),local);
    if(info.storageEntries)note('localStorage: '+info.storageEntries.local+' записей · sessionStorage: '+info.storageEntries.session+' записей',local);if(info.trackerHosts.length)code(info.trackerHosts.join('\n'),local);note('Список трекеров ограничен встроенными правилами. Это не полная защита от отслеживания.',local);
    for(const [key,label]of [['media','Камера / микрофон'],['geolocation','Местоположение'],['notifications','Уведомления'],['clipboard-read','Буфер обмена']]){const s=select(label,[['block','Запретить'],['allow','Разрешить']],local,info.permissions[key]||info.defaults[key]);s.onchange=guard(()=>api.call('settings',{sitePermissions:{...state.settings.sitePermissions,[info.origin]:{...state.settings.sitePermissions[info.origin],[key]:s.value}}}));}
    btn('Сбросить разрешения сайта',async()=>{await invoke('privacy:reset');await draw();},local);
    const confirm=check('Удалить данные этого сайта и завершить вход на нём',local);btn('Очистить cookies',async()=>{if(!confirm.checked)throw Error('Подтвердите очистку данных сайта.');await invoke('privacy:clear',{cookiesOnly:true});await draw();},local);btn('Очистить все данные сайта',async()=>{if(!confirm.checked)throw Error('Подтвердите очистку данных сайта.');await invoke('privacy:clear');await draw();},local);
    note('Маршрут: '+info.route.profileName+' · DNS: '+info.route.dns+' · WebRTC: '+info.route.webrtc,local);btn('Настроить сеть',()=>api.call('panel','connection'),local);btn('Cookie & Storage Viewer',()=>window.kernelTools.run('storage'),local);
   }else{
    heading(info.security.https?'HTTPS':'HTTP · соединение не зашифровано',info.security.tls?.protocol||'TLS ещё не записан',local);code(info.security.tls||'Для сведений о сертификате включите запись и обновите страницу.',local);
    btn('Записать TLS и обновить страницу',async()=>{await invoke('security:record');await api.call('reload');window.kernelUI.toast('После загрузки нажмите «Обновить сведения».');},local);btn('Обновить сведения',()=>draw(),local);
    code(info.security.headers,local);code(info.security.cookies,local);code(info.security.redirects,local);note('Попытки смешанного содержимого: '+info.security.mixedContent.join(', '),local);note(info.security.limitations,local);
    note('Риски загруженных файлов: исполняемые файлы, сценарии и HTTP-источники требуют проверки перед запуском.',local);for(const d of state.downloads.slice(0,20)){const flags=[!String(d.url).startsWith('https:')?'HTTP / неизвестный источник':'',/\.(exe|msi|bat|cmd|ps1|vbs|scr|js)$/i.test(d.name)?'Исполняемый файл / сценарий':''].filter(Boolean);heading(d.name,flags.join(' · ')||'Автоматическая оценка не заменяет проверку файла',local);}
   }
  }else if(section==='performance'){
   note('Метрики процессов Chromium. RAM общего процесса может отображаться у нескольких вкладок; итог учитывает процесс один раз.',local);btn('Усыпить безопасные фоновые вкладки',async()=>{const r=await invoke('tabs:optimize');window.kernelUI.toast('Усыплено '+r.filter(x=>x.slept).length+' вкладок.');await sample();},local);
   const stats=el('div');local.append(stats);let sampling=false;
   async function sample(){if(sampling)return;sampling=true;try{const m=await invoke('performance:get');if(!alive())return;stats.replaceChildren();heading(bytes(m.ramKB*1024)+' RAM · '+m.cpu.toFixed(1)+'% CPU',m.tabCount+' вкладок · '+new Date(m.sampledAt).toLocaleTimeString(),stats);for(const t of m.tabs){const item=el('article',undefined,'advanced-item');heading(t.title,(t.sleeping?'Спит':bytes(t.ramKB*1024)+' · '+t.cpu.toFixed(1)+'% CPU')+' · '+t.requests+' запросов'+(t.active?' · Активная':''),item);btn(t.sleeping?'Разбудить':'Усыпить',async()=>{const r=await invoke(t.sleeping?'tab:restore':'tab:sleep',{id:t.id});if(r?.reason)window.kernelUI.toast(r.reason);await sample();},item);stats.append(item);}const detail=el('details');detail.append(el('summary','GPU и процессы'));code({features:m.gpu,processes:m.processes},detail);stats.append(detail);note(m.note,stats);}finally{sampling=false;}}
   await sample();poll=setInterval(()=>guard(sample)(),2500);
  }else if(section.startsWith('search-')){
   const kind=section==='search-history'?'history':'bookmarks',search=field('Поиск',query,local,'search'),results=el('div');local.append(results);
   const load=async()=>{const r=await invoke('search',{kind,query:search.value});if(!alive())return;results.replaceChildren();for(const item of r.items)btn(item.title+'\n'+item.url,()=>api.call('navigate',item.url),results,'advanced-search-result');};search.oninput=guard(load);await load();
  }
 }
 function bytes(value=0){return value>=1073741824?(value/1073741824).toFixed(2)+' ГБ':(value/1048576).toFixed(1)+' МБ';}
 function editNote(item,parent){
  parent.replaceChildren();btn('Все заметки',()=>draw(),parent);const url=field('URL',item.url||state.tabs.find(t=>t.id===state.activeId)?.url,parent),text=field('Текст',item.text,parent,'textarea'),selection=field('Исходное выделение',item.selection,parent,'textarea'),tags=field('Теги через запятую',(item.tags||[]).join(', '),parent);text.rows=12;
  btn('Сохранить',async()=>{await invoke('notes:save',{id:item.id,url:url.value,text:text.value,selection:selection.value,tags:tags.value.split(',').map(x=>x.trim()).filter(Boolean)});await draw();},parent);if(item.id)btn('Удалить заметку',async()=>{await invoke('notes:delete',{id:item.id});await draw();},parent);text.focus();
 }
 async function capsuleForm(parent){
  parent.replaceChildren();btn('Библиотека',()=>draw(),parent);const notes=field('Заметка','',parent,'textarea'),summary=field('Краткое содержание / ответ ИИ (необязательно)','',parent,'textarea'),chosen=new Set();
  btn('Взять последний ответ чата',()=>{const messages=document.querySelectorAll('.chat-message.assistant .message-content');const text=messages[messages.length-1]?.innerText;if(!text)throw Error('Сначала получите краткое содержание страницы в чате.');summary.value=text;},parent);
  btn('Сохранить Capsule',async()=>{await invoke('capsules:save',{notes:notes.value,summary:summary.value,images:[...chosen]});await draw();window.kernelUI.toast('Страница сохранена офлайн.');},parent);
  btn('Выбрать изображения',async()=>{const images=await invoke('capsules:images');for(const image of images){const i=check(image.url,parent);i.onchange=()=>{if(i.checked&&chosen.size>=8){i.checked=false;window.kernelUI.toast('Можно выбрать до 8 изображений.');return;}i.checked?chosen.add(image.url):chosen.delete(image.url);};}note('До 8 растровых изображений по 1 МБ. Ограниченные или недоступные ресурсы пропускаются.',parent);},parent);
 }
 function showCapsule(c){content.replaceChildren();btn('Библиотека',()=>draw(),content);heading(c.title,new Date(c.at).toLocaleString()+' · '+c.url,content);if(c.summary)note(c.summary,content);const article=el('article',c.text,'capsule-reader');content.append(article);for(const image of c.images){const img=el('img');img.src=image.data;img.alt='Сохранённое изображение';img.className='capsule-image';content.append(img);}if(c.notes)note('Заметки: '+c.notes,content);btn('Открыть исходный сайт',()=>api.call('tab:new',c.url),content);}

 // Existing settings are extended in place; data-setting controls use the same validated backend.
 const settingsNav=document.querySelector('.settings-nav'),settingsRoot=document.querySelector('[data-section=general]').parentElement;
 const labels={tabs:'Вкладки',ghost:'Ghost Mode',tor:'Tor',performance:'Производительность',shortcuts:'Сочетания клавиш',workspaces:'Workspaces',security:'Безопасность',advanced:'Дополнительно'};
 const shortcuts=[['Ctrl K','Командная строка'],['Ctrl Shift A','ИИ'],['Ctrl Shift P','Приватность сайта'],['Ctrl Shift G','Ghost Mode'],['Ctrl Shift W','Workspaces'],['Ctrl Shift N','Новый workspace'],['Ctrl Shift S','Page Capsule']];
 for(const [id,label]of Object.entries(labels)){
  const b=btn(label,()=>showSettingsSection(id),settingsNav);b.dataset.settingsPage=id;
  const s=el('section',undefined,'settings-section hidden');s.dataset.section=id;s.append(el('h2',label));settingsRoot.append(s);
  if(id==='tabs'){setting(s,'Автоматически усыплять неактивные вкладки','autoSleep','checkbox',null,'Вкладки с формами, звуком или видео остаются в памяти.');setting(s,'Через сколько минут','sleepMinutes','number',null,'От 1 до 240 минут. Активные и закреплённые вкладки защищены.');btn('Управление вкладками',()=>open('tabs'),s);}
  if(id==='ghost'){note('Ghost открывает отдельное окно с временным профилем, отдельными cookies и без истории посещений. Данные удаляются после закрытия окна. Это не гарантия анонимности.',s);setting(s,'Маршрут нового окна','ghostRoute','select',[['direct','Обычное подключение'],['tor','Tor через существующий Connection']]);btn('Открыть Ghost Mode',()=>invoke('ghost:new'),s);}
  if(id==='tor'){note('Tor использует существующий Connection. При недоступности сети действует выбранная политика Kill Switch. Настройки fingerprint не изменяются.',s);btn('Настройки Tor / Connection',()=>api.call('panel','connection'),s);}
  if(id==='performance'){note('Реальные показатели процессов CPU и RAM, состояние GPU, фоновые страницы и безопасное освобождение памяти.',s);btn('Открыть Performance Center',()=>open('performance'),s);}
  if(id==='workspaces'){setting(s,'Кнопка workspace в sidebar','showWorkspaceButton','checkbox');note('Изменённые формы необходимо сохранить перед переключением. Рабочие пространства принадлежат текущему локальному аккаунту.',s);btn('Управление workspaces',()=>open('workspaces'),s);}
  if(id==='shortcuts')for(const [key,description]of shortcuts){const r=row(s);r.append(el('kbd',key),el('span',description));}
  if(id==='security'){note('Пассивная проверка текущего сайта: TLS, защитные заголовки, cookies, редиректы и смешанное содержимое. Не выполняет сканирование или эксплуатацию.',s);btn('Открыть Security Center',()=>open('security'),s);}
  if(id==='advanced'){note('Сброс возвращает стандартное оформление и поведение. Аккаунты, данные сайтов и загрузки сохраняются.',s);btn('Восстановить настройки по умолчанию',()=>api.call('settings:reset'),s);btn('API Inspector',()=>window.kernelTools.run('network'),s);}
 }
 setting(document.querySelector('[data-section=privacy]'),'Блокировать известные трекеры','trackerBlocking','checkbox',null,'Правила для конкретного сайта можно изменить в Privacy Center.');
 const aiSettings=document.querySelector('[data-section=ai]');aiSettings.querySelector('.settings-card .setting-row').remove();aiSettings.querySelector('.setting-note').textContent='Контекст передаётся только по вашему выбору. Настройки применяются к следующему запросу.';setting(aiSettings,'Провайдер','aiProvider','select',[['local','Локальная модель · llama.cpp'],['compatible','Совместимый Chat Completions API']]);
 const modelLabel=el('p','Локальная модель. Квантизация определяется выбранным GGUF-файлом.','setting-note');aiSettings.append(modelLabel);btn('Выбрать локальную модель GGUF',()=>api.call('ai:model-select'),aiSettings);btn('Вернуть встроенную модель',()=>api.call('settings',{aiModelFile:'',aiProvider:'local'}),aiSettings);
 const endpoint=field('Адрес API (например http://127.0.0.1:11434/v1)','',aiSettings),model=field('Имя модели API','',aiSettings),key=field('API key · пустое поле сохраняет текущий ключ','',aiSettings,'password');key.autocomplete='new-password';const removeKey=check('Удалить сохранённый API key',aiSettings);
 btn('Сохранить API',async()=>{await api.call('ai:provider',{endpoint:endpoint.value,model:model.value,...(key.value||removeKey.checked?{key:key.value}:{})});key.value='';removeKey.checked=false;window.kernelUI.toast('Настройки API сохранены.');},aiSettings);note('Для внешнего API перед каждым сообщением требуется явное согласие на передачу текста. Ключ хранится зашифрованным средствами Windows. Модель и API-сервер устанавливаются отдельно.',aiSettings);
 for(const [name,values]of [['aiContext',[16384,32768]],['aiMaxTokens',[8192]]]){const select=document.querySelector('select[data-setting='+name+']');for(const n of values){const o=el('option',n+' токенов');o.value=n;select.append(o);}}
 function setting(parent,label,name,type,options,description){const l=el('label',undefined,'setting-row'),span=el('span');span.append(el('strong',label));if(description)span.append(el('small',description));let i;
  if(type==='select'){i=el('select');for(const [v,t]of options){const o=el('option',t);o.value=v;i.append(o);}}else{i=el('input');i.type=type;if(type==='checkbox')i.className='switch';if(type==='number'){i.min=1;i.max=240;}}i.dataset.setting=name;if(type==='number')i.dataset.number='';i.onchange=guard(()=>api.call('settings',{[name]:type==='checkbox'?i.checked:type==='number'?Number(i.value):i.value}));l.append(span,i);parent.append(l);return i;
 }

 const contextBox=el('details',undefined,'ai-context-options');contextBox.append(el('summary','Контекст и передача данных'));$('chat-form').before(contextBox);const chosenTabs=new Set(),tabsBox=el('div');contextBox.append(tabsBox);const remoteConsent=check('Разрешаю отправить это сообщение и выбранный контекст провайдеру API',contextBox);const consentLabel=remoteConsent.parentElement;
 const oldContextTip=document.querySelector('.page-context .info-tip');oldContextTip.title='Текст и выделение передаются только при отправке. Для внешнего API требуется отдельное согласие.';
 function aiRequest(){const compatible=state?.settings.aiProvider==='compatible';let remote=false;try{remote=!['localhost','127.0.0.1','[::1]'].includes(new URL(state.aiProvider.endpoint).hostname);}catch{}if(compatible&&remote&&!remoteConsent.checked){window.kernelUI.toast('Подтвердите передачу сообщения внешнему API в разделе «Контекст и передача данных».');contextBox.open=true;return false;}const consent=remoteConsent.checked;remoteConsent.checked=false;return{context:chosenTabs.size?{tabIds:[...chosenTabs]}:$('page-context').checked,remoteConsent:consent};}

 // One resolver serves both the existing command palette and the address autocomplete.
 async function execute(item){if(item.type==='tool'){await api.call('palette:set',false);$('command-palette').classList.add('hidden');hideAddress(false);return window.kernelTools.run(item.id);}const result=await api.call('command:run',item);await api.call('palette:set',false);$('command-palette').classList.add('hidden');hideAddress(false);$('address').blur();if(item.type==='calculator')window.kernelUI.toast('Скопировано: '+item.value);return result;}
 function paintPalette(){const list=$('command-results');list.replaceChildren();paletteIndex=Math.max(0,Math.min(paletteIndex,paletteRows.length-1));paletteRows.forEach((item,i)=>{const b=el('button',undefined,'palette-command'+(i===paletteIndex?' selected':''));b.append(el('span',item.title),el('small',item.hint));b.onclick=guard(()=>execute(item));list.append(b);});list.children[paletteIndex]?.scrollIntoView({block:'nearest'});}
 async function paletteSearch(){paletteRows=[];paintPalette();const token=++paletteGeneration,q=$('command-query').value,commands=window.kernelCommands.filter(c=>(c.title+' '+c.hint+' '+c.group).toLowerCase().includes(q.toLowerCase())).map(c=>({type:'tool',id:c.id,title:c.title,hint:c.group})),results=q?await api.call('command:suggest',q):[];if(token!==paletteGeneration)return;paletteRows=[...results,...commands.filter(c=>!results.some(r=>r.type==='tool'&&r.id===c.id))];paletteIndex=0;paintPalette();}
 const paletteOpen=window.kernelTools.openPalette;window.kernelTools.openPalette=()=>{paletteOpen();guard(paletteSearch)();};api.on('palette-open',()=>guard(paletteSearch)());
 $('command-query').oninput=()=>guard(paletteSearch)();$('command-query').onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();paletteIndex+=e.key==='ArrowDown'?1:-1;paintPalette();}if(e.key==='Enter'){e.preventDefault();if(paletteRows[paletteIndex])guard(()=>execute(paletteRows[paletteIndex]))();}if(e.key==='Escape'){api.call('palette:set',false);$('command-palette').classList.add('hidden');}};
 const addressList=el('div',undefined,'address-suggestions hidden');addressList.id='address-suggestions';addressList.setAttribute('role','listbox');$('address-form').append(addressList);$('address').setAttribute('role','combobox');$('address').setAttribute('aria-controls',addressList.id);$('address').setAttribute('aria-autocomplete','list');
 function hideAddress(restore=true){addressGeneration++;addressList.classList.add('hidden');$('address').setAttribute('aria-expanded','false');if(restore&&addressOverlay&&$('command-palette').classList.contains('hidden'))api.call('palette:set',false);addressOverlay=false;}
 function paintAddress(){addressList.replaceChildren();addressIndex=Math.max(0,Math.min(addressIndex,addressRows.length-1));addressRows.forEach((item,i)=>{const b=el('button',undefined,'address-suggestion'+(i===addressIndex?' selected':''));b.id='address-option-'+i;b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',i===addressIndex);b.append(el('span',item.title),el('small',item.hint));b.onmousedown=e=>e.preventDefault();b.onclick=guard(()=>execute(item));addressList.append(b);});$('address').setAttribute('aria-activedescendant','address-option-'+addressIndex);}
 $('address').addEventListener('input',guard(async()=>{const token=++addressGeneration,value=$('address').value;addressRows=[];addressList.classList.add('hidden');if(!value.trim()){hideAddress();return;}const rows=await api.call('command:suggest',value);if(token!==addressGeneration||document.activeElement!==$('address'))return;addressRows=rows;addressIndex=0;paintAddress();addressList.classList.toggle('hidden',!rows.length);$('address').setAttribute('aria-expanded',!!rows.length);addressOverlay=!!rows.length;await api.call('palette:set',addressOverlay);}));
 $('address').addEventListener('keydown',e=>{if(addressList.classList.contains('hidden'))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();addressIndex+=e.key==='ArrowDown'?1:-1;paintAddress();}if(e.key==='Escape'){e.preventDefault();hideAddress();$('address').blur();}if(e.key==='Enter'&&addressRows[addressIndex]){e.preventDefault();e.stopImmediatePropagation();const item=addressRows[addressIndex];$('address').blur();guard(()=>execute(item))();}},true);
 $('address').addEventListener('blur',()=>setTimeout(()=>{if(addressOverlay)hideAddress();},100));

 let tabsSignature='',providerSignature='',identity='';
 window.kernelAdvanced={handles:id=>!!aliases[id]||['tabs','workspaces','notes','capsules','privacy','performance','security','ghost'].includes(id),open,aiRequest,render(s){
  const old=state;state=s;panel.classList.toggle('hidden',s.panel!=='advanced');if(s.panel!=='advanced'){clearInterval(poll);generation++;}else if(old?.panel!=='advanced')guard(()=>draw())();
  const workspace=s.advanced?.workspaces.find(w=>w.id===s.advanced.workspaceId);workspaceButton.textContent=(workspace?.icon||'◻')+' '+(workspace?.name||'Основное');workspaceButton.style.color=workspace?.accent||'';workspaceButton.classList.toggle('hidden',!s.settings.showWorkspaceButton);ghostBadge.classList.toggle('hidden',!s.advanced?.ghost);document.body.classList.toggle('ghost-mode',!!s.advanced?.ghost);
  const sig=contextBox.open?JSON.stringify(s.tabs.map(t=>[t.id,t.title,t.sleeping])):'';if(contextBox.open&&sig!==tabsSignature){tabsSignature=sig;tabsBox.replaceChildren();note('Дополнительные вкладки (до 8). Текст спящих вкладок не читается.',tabsBox);for(const t of s.tabs.filter(t=>t.url.startsWith('http'))){const c=check(t.title,tabsBox,chosenTabs.has(t.id));c.disabled=t.sleeping;c.onchange=()=>{if(c.checked&&chosenTabs.size>=8){c.checked=false;window.kernelUI.toast('Можно добавить до 8 вкладок.');return;}c.checked?chosenTabs.add(t.id):chosenTabs.delete(t.id);};}for(const id of chosenTabs)if(!s.tabs.some(t=>t.id===id))chosenTabs.delete(id);}
  consentLabel.classList.toggle('hidden',s.settings.aiProvider!=='compatible');consentLabel.querySelector('span').textContent='Разрешаю отправить это сообщение и выбранный контекст: '+(s.aiProvider?.endpoint||'API');const p=JSON.stringify(s.aiProvider);modelLabel.textContent=s.settings.aiProvider==='compatible'?'Chat Completions API · модель: '+(s.aiProvider?.model||'не настроена'):(s.ai?.model+' · '+s.ai?.parameters+' · '+s.ai?.quantization);if(p!==providerSignature){providerSignature=p;if(document.activeElement!==endpoint)endpoint.value=s.aiProvider?.endpoint||'';if(document.activeElement!==model)model.value=s.aiProvider?.model||'';key.placeholder=s.aiProvider?.hasKey?'Ключ сохранён · пустое поле не изменяет его':'API key';}
  const id=s.account?.id+':'+s.advanced?.workspaceId;if(identity&&identity!==id){remoteConsent.checked=false;chosenTabs.clear();if(s.panel==='advanced')guard(()=>draw())();}identity=id;
 }};
 api.on('advanced-open',payload=>{section=payload.section;guard(async()=>{state=await api.call('state');panel.classList.remove('hidden');await draw(payload.query);})();});api.on('settings-open',name=>showSettingsSection(name));
 contextBox.addEventListener('toggle',()=>{if(contextBox.open&&state)window.kernelAdvanced.render(state);});if(current){window.kernelAdvanced.render(current);renderSettings();}else api.call('state').then(s=>{window.kernelAdvanced.render(s);renderSettings();});
}
if(document.readyState==='complete')setTimeout(initializeAdvanced,0);else addEventListener('load',()=>setTimeout(initializeAdvanced,0),{once:true});
