const fs=require('node:fs/promises'),path=require('node:path'),{assetName,safeName}=require('./pure.cjs');
const escapeRE=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function saveArchive({wc,page,root,mode='snapshot',log,signal}){
  if(!['snapshot','editable','single'].includes(mode))throw Error('Неизвестный режим сохранения.');const folder=path.join(root,safeName(new URL(page.url).hostname)+'-'+Date.now());await fs.mkdir(path.join(folder,'assets'),{recursive:true});log('CAPTURE',page.title);const single=mode==='single';let total=0;const saved=new Map(),failures=[],queue=[...page.assets].filter(a=>['http:','https:'].includes(new URL(a.url).protocol));
  async function fetchAsset(item){if(signal?.aborted)throw Error('Сохранение отменено.');if(saved.has(item.url)||queue.length>600)return;const name=assetName(item.url);saved.set(item.url,{name,pending:true});try{const res=await wc.session.fetch(item.url,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(25000)]):AbortSignal.timeout(25000)});if(!res.ok)throw Error('HTTP '+res.status);const type=res.headers.get('content-type')||'application/octet-stream',chunks=[];let length=0;for await(const chunk of res.body){length+=chunk.length;total+=chunk.length;if(length>40*1024*1024||total>300*1024*1024)throw Error('Ресурс превышает лимит сохранения.');chunks.push(chunk);}const bytes=Buffer.concat(chunks);const rec={name,type,bytes};saved.set(item.url,rec);log('FETCH',safeName(new URL(item.url).pathname)+' · '+Math.round(length/1024)+' KB');if(/css/i.test(type)||/\.css(?:\?|$)/i.test(item.url)){rec.text=bytes.toString('utf8');for(const m of rec.text.matchAll(/(?:url\(\s*['"]?([^'"\)\s]+)['"]?\s*\)|@import\s+['"]([^'"]+)['"])/g)){try{const u=new URL(m[1]||m[2],item.url);if(/^https?:$/.test(u.protocol)&&!saved.has(u.href)&&!queue.some(a=>a.url===u.href))queue.push({url:u.href,type:'css-asset'});}catch{}}}}catch(e){saved.delete(item.url);failures.push({url:item.url,error:e.message});log('SKIP',safeName(new URL(item.url).pathname)+' · '+e.message);}}
  let cursor=0;while(cursor<queue.length&&cursor<600){const batch=queue.slice(cursor,cursor+6);cursor+=batch.length;await Promise.all(batch.map(fetchAsset));}
  const resourceURL=(url,fromCSS=false)=>{const r=saved.get(url);if(!r||r.pending)return url;if(single)return 'data:'+r.type+';base64,'+r.bytes.toString('base64');return (fromCSS?'':'assets/')+r.name;};
  if(single){const done=new Set();const materialize=(url,stack=new Set())=>{const r=saved.get(url);if(!r?.text||done.has(url))return;if(stack.has(url))return;stack.add(url);r.text=r.text.replace(/url\(\s*(['"]?)([^'"\)]+)\1\s*\)/g,(m,q,ref)=>{if(ref.trim().startsWith('#'))return m;try{const u=new URL(ref.trim(),url).href;if(stack.has(u))return m;materialize(u,new Set(stack));return 'url("'+resourceURL(u,true)+'")';}catch{return m;}}).replace(/@import\s+(['"])([^'"]+)\1/g,(m,q,ref)=>{try{const u=new URL(ref,url).href;if(stack.has(u))return m;materialize(u,new Set(stack));return '@import '+q+resourceURL(u,true)+q;}catch{return m;}});r.bytes=Buffer.from(r.text);done.add(url);};for(const url of saved.keys())materialize(url);}
  // Resolve CSS imports and URLs against their own stylesheet, then write assets.
  for(const [url,r]of saved){if(!r.text)continue;r.text=r.text.replace(/url\(\s*(['"]?)([^'"\)]+)\1\s*\)/g,(_m,_q,ref)=>{try{return 'url("'+resourceURL(new URL(ref.trim(),url).href,true)+'")';}catch{return _m;}}).replace(/@import\s+(['"])([^'"]+)\1/g,(_m,q,ref)=>{try{return '@import '+q+resourceURL(new URL(ref,url).href,true)+q;}catch{return _m;}});r.bytes=Buffer.from(r.text);}
  // Static copies deliberately do not execute scripts from the original site.
  let html=page.html.replace(/<base\b[^>]*>/gi,'').replace(/<meta\b[^>]*http-equiv\s*=\s*['"]?(?:content-security-policy|refresh)[^>]*>/gi,'');if(mode!=='editable')html=html.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,'').replace(/\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*')/gi,'');
  const replacements=[];for(const [url,r]of saved){const local=resourceURL(url);replacements.push([url,local],[url.replaceAll('&','&amp;'),local]);try{const u=new URL(url);if(u.origin===new URL(page.url).origin){replacements.push([u.pathname+u.search,local],[u.pathname+u.search.replaceAll('&','&amp;'),local]);const rel=path.posix.relative(path.posix.dirname(new URL(page.url).pathname),u.pathname)+(u.search||'');if(rel)replacements.push([rel,local]);}}catch{}}
  replacements.sort((a,b)=>b[0].length-a[0].length);for(const [from,to]of replacements){if(from.length>1)html=html.replace(new RegExp('(["\'\(=\\s])'+escapeRE(from)+'(?=["\'\)\\s>,])','g'),(_m,prefix)=>prefix+to);}
  if(page.css)html=html.replace('</head>','<style data-kernel-capture>'+page.css.replace(/url\(\s*(['"]?)([^'"\)]+)\1\s*\)/g,(m,q,ref)=>{try{return 'url("'+resourceURL(new URL(ref,page.url).href)+'")';}catch{return m;}})+'</style></head>');
  if(!single)for(const r of saved.values())if(!r.pending){await fs.writeFile(path.join(folder,'assets',r.name),r.bytes);log('WRITE','assets/'+r.name);}
  const file=path.join(folder,'index.html');await fs.writeFile(file,html);await fs.writeFile(path.join(folder,'capture.json'),JSON.stringify({title:page.title,url:page.url,at:Date.now(),mode,assets:saved.size,bytes:total,failures},null,2));log('DONE',saved.size+' assets · '+Math.round(total/1024)+' KB');return{folder,file,assets:saved.size,failures,bytes:total};
}
module.exports={saveArchive};
