(()=>{
const commands=[
 ['save','Сохранить страницу','Страница','HTML, CSS и ресурсы'],['inspect','Выбрать элемент','Разработка','HTML, CSS, размеры'],['copy-style','Копировать стиль','Разработка','CSS / Tailwind / цвет / шрифт'],['screenshot','Скриншот','Страница','Вся страница / область / элемент'],['pdf','Сохранить PDF','Страница','Чистая статья или исходная страница'],['reader','Режим чтения','Страница','Основной текст без боковых панелей'],['assets','Ресурсы страницы','Разработка','Изображения, CSS, JS, шрифты'],['colors','Цвета и пипетка','Разработка','Палитра страницы'],['fonts','Шрифты','Разработка','Список и инспектор текста'],['responsive','Адаптивный просмотр','Разработка','Телефон, планшет, свой размер'],['split','Разделить просмотр','Вкладки','Два сайта рядом'],['links','Собрать ссылки','Страница','Внутренние и внешние'],['qr','QR-код','Страница','Адрес или выделенный текст'],['markdown','Сохранить Markdown','Страница','Выделение или статья'],['note','Заметка к странице','Страница','Сохраняется для этого URL'],['edit','Временное редактирование','Разработка','Текст, изображения, CSS'],['diff','Сравнить страницу','Разработка','Снимок и изменения текста'],['json','JSON Viewer','Разработка','Дерево, поиск, копирование пути'],['network','API Inspector','Разработка','Запросы, ответы и время'],['storage','Cookies и хранилище','Разработка','Cookies, localStorage, sessionStorage'],['permissions','Разрешения сайта','Connection','Камера, микрофон, геолокация, clipboard'],['redirects','Цепочка редиректов','Connection','Проверить текущий адрес'],['clean-url','Копировать чистую ссылку','Страница','Без tracking-параметров'],['duplicates','Одинаковые вкладки','Вкладки','Найти и закрыть дубликаты'],['sleep','Усыпить неактивные вкладки','Вкладки','Освободить память'],['workspace','Снимки вкладок','Вкладки','Сохранить и восстановить вкладки'],['downloads','Загрузки','Вкладки','Поиск, пауза, продолжение'],['palette','Палитра команд','Kernel','Ctrl K'],['page-actions','Действия страницы','Страница','Доступны также по правому клику'],['ai-page','Спросить ИИ о странице','Страница','Только текущая страница или выделение'],['smart-search','Поиск в браузере','Kernel','tabs: / history: / bookmarks:'],['focus','Режим фокуса','Kernel','Только страница · Esc — выход'],['pip','Видео поверх окон','Страница','Picture-in-Picture+'],['clipboard','История копирования','Kernel','Только копирования внутри Kernel'],['convert','Преобразования','Разработка','Единицы, даты, JSON, Base64, URL'],['archive','Архив страниц','Страница','Локальные копии с поиском'],
 ['connection','Kernel Connection','Connection','Маршруты вкладок и правила'],['route-direct','Connection: Use Direct','Connection','Текущая вкладка'],['route-smart','Connection: Use Smart Route','Connection','Правила сайта'],['route-tunnel','Connection: Use Secure Tunnel','Connection','Tor'],['route-proxy','Connection: Select Profile','Connection','Пользовательский прокси'],['route-site','Connection: Route Current Site','Connection','Запомнить для сайта'],['route-disconnect','Connection: Disconnect','Connection','Вернуть Direct'],['route-rules','Connection: Manage Site Rules','Connection','Правила маршрутизации'],['bypass','Обход DPI · zapret','Connection','Действует на компьютер · UAC Windows']
].map(([id,title,group,hint])=>({id,title,group,hint}));

commands.sort((a,b)=>['Страница','Разработка','Вкладки','Kernel','Connection'].indexOf(a.group)-['Страница','Разработка','Вкладки','Kernel','Connection'].indexOf(b.group));

if(typeof module!=='undefined'&&module.exports)module.exports=commands;else window.kernelCommands=commands;
})();
