const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {BrowserWindow,WebContentsView,clipboard,shell}=require('electron');const {atomicWrite,readJSON}=require('../core.cjs');const page=require('./page.cjs');const {saveArchive}=require('./archive.cjs');const {cleanURL,safeName,textDiff,convert}=require('./pure.cjs');const Turndown=require('turndown'),QR=require('qrcode');
const invoke=(wc,fn,...args)=>wc.executeJavaScript('('+fn.toString()+')('+args.map(a=>JSON.stringify(a)).join(',')+')',true);
const escapeHTML=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
class ToolService{
  constructor(api){Object.assign(this,api);this.file=path.join(this.root,'tools.json');this.data={notes:{},snapshots:{},workspaces:[],archive:[],...readJSON(this.file,{})};this.logs=[];this.jobs=new Map();this.clipboard=[];this.network=new Map();this.networkHandlers=new Map();this.aux=[];this.focus=false;this.lastInspect=null;this.responsive=null;this.splitId='';this.live=true;}
  tab(){return this.tabs.find(t=>t.id===this.activeId());}
  wc(){const wc=this.tab()?.view?.webContents;if(!wc||wc.isDestroyed())throw Error('Сначала откройте страницу сайта.');return wc;}
  save(){atomicWrite(this.file,this.data);}
  info(){return{archive:this.data.archive.slice(0,100).map(a=>({id:a.id,title:a.title,url:a.url,at:a.at})),workspaces:this.data.workspaces,notes:this.data.notes[this.tab()?.url]||'',logs:this.logs.slice(-250),focus:this.focus,responsive:this.responsive,splitId:this.splitId,clipboard:this.clipboard.map(x=>({text:x.text,at:x.at})),inspector:this.lastInspect?{tag:this.lastInspect.tag,rect:this.lastInspect.rect}:null,jobs:[...this.jobs].map(([id,j])=>({id,title:j.title}))};}
  log(type,text){const line={at:Date.now(),type,text:String(text).slice(0,300)};this.logs.push(line);if(this.logs.length>1000)this.logs.shift();this.emit('tools-log',line);}
  async copy(text){text=String(text).slice(0,2000000);await clipboard.writeText(text);await this.remember(text);return{copied:true,text};}
  async remember(text){if(text===undefined)text=await clipboard.readText();if(typeof text!=='string'||!text||text.length>100000)return;this.clipboard=this.clipboard.filter(x=>x.text!==text);this.clipboard.unshift({text,at:Date.now()});this.clipboard.length=Math.min(30,this.clipboard.length);this.changed();}
  async snapshot(){return invoke(this.wc(),page.inventory);}
  async inspect(area=false,reopen=true){this.closePanel();const result=await invoke(this.wc(),page.pick,page.inspectElement.toString(),area);if(result&&!area)this.lastInspect=result;if(reopen)this.openPanel('tools');this.changed();return result;}
  async article(){const wc=this.wc(),source=fs.readFileSync(require.resolve('@mozilla/readability/Readability.js'),'utf8'),purify=fs.readFileSync(require.resolve('dompurify/dist/purify.min.js'),'utf8');return wc.executeJavaScript('(()=>{'+source+'\n'+purify+'\nconst r=new Readability(document.cloneNode(true)).parse();const content=DOMPurify.sanitize(r?.content||document.querySelector("main,article")?.innerHTML||document.body.innerHTML,{FORBID_TAGS:["form","iframe","style"]});const holder=document.createElement("div");holder.innerHTML=content;for(const el of holder.querySelectorAll("[src],[href]"))for(const key of ["src","href"])if(el.hasAttribute(key)){try{el.setAttribute(key,new URL(el.getAttribute(key),document.baseURI).href);}catch{}}return {title:r?.title||document.title,content:holder.innerHTML,text:r?.textContent||document.body.innerText,url:location.href};})()',true);}
  async directory(){const root=this.exportRoot||path.join(this.app.getPath('desktop'),'sites');await fsp.mkdir(root,{recursive:true});return root;}
  async savePage(mode){if(this.jobs.size)throw Error('Дождитесь текущего сохранения или отмените его.');const wc=this.wc(),snapshot=await this.snapshot(),root=await this.directory(),id=crypto.randomUUID(),controller=new AbortController();this.jobs.set(id,{title:'Сохранение страницы',controller});this.changed();try{const result=await saveArchive({wc,page:snapshot,root,mode,signal:controller.signal,log:(...a)=>this.log(...a)});const record={id,title:snapshot.title,url:snapshot.url,at:Date.now(),...result,text:snapshot.text.slice(0,80000)};const image=await wc.capturePage();await fsp.writeFile(path.join(result.folder,'preview.png'),image.resize({width:640}).toPNG());record.preview='data:image/png;base64,'+image.resize({width:320}).toPNG().toString('base64');this.data.archive.unshift(record);this.data.archive=this.data.archive.slice(0,100);this.save();this.changed();return result;}finally{this.jobs.delete(id);this.changed();}}
  async screenshot(kind){const wc=this.wc();let clip;if(kind==='area'||kind==='element'){const selected=await this.inspect(kind==='area',false);if(!selected)return;clip=selected.pageRect;}if(!wc.debugger.isAttached())wc.debugger.attach('1.3');const m=await wc.debugger.sendCommand('Page.getLayoutMetrics');if(!clip)clip={x:0,y:0,width:m.cssContentSize.width,height:m.cssContentSize.height};clip={x:Math.max(0,clip.x),y:Math.max(0,clip.y),width:Math.max(1,Math.min(16000,clip.width)),height:Math.max(1,Math.min(32760,clip.height)),scale:1};const image=await wc.debugger.sendCommand('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,fromSurface:true,clip});const root=await this.directory(),file=path.join(root,safeName(this.tab().title)+'-'+Date.now()+'.png');await fsp.writeFile(file,Buffer.from(image.data,'base64'));this.log('PNG',path.basename(file)+' · '+Math.round(clip.width)+' × '+Math.round(clip.height));this.openPanel('tools');return{file,width:clip.width,height:clip.height};}
  async pdf(clean=true){const source=this.wc();let temporary;try{let target=source;if(clean){const article=await this.article();temporary=new BrowserWindow({show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,session:source.session}});target=temporary.webContents;target.setWindowOpenHandler(()=>({action:'deny'}));await target.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src https: http: data:; style-src \'unsafe-inline\'"><style>body{font:12pt Georgia;line-height:1.65;max-width:700px;margin:40px auto;color:#111}img{max-width:100%}pre{white-space:pre-wrap}h1{font:24pt Georgia}a{color:inherit}header{font:9pt Arial;color:#555}</style><header>'+escapeHTML(article.url)+'</header><h1>'+escapeHTML(article.title)+'</h1>'+article.content));}const bytes=await target.printToPDF({printBackground:false,preferCSSPageSize:true,pageSize:'A4',margins:{top:.5,bottom:.5,left:.5,right:.5}}),root=await this.directory(),file=path.join(root,safeName(this.tab().title)+'-'+Date.now()+'.pdf');await fsp.writeFile(file,bytes);this.log('PDF',path.basename(file));return{file};}finally{temporary?.destroy();}}
  async markdown(){const selected=await invoke(this.wc(),page.selectionHTML),a=selected?{title:this.tab().title,content:selected,url:this.tab().url}:await this.article();const text='# '+a.title+'\n\n'+new Turndown({headingStyle:'atx',codeBlockStyle:'fenced'}).turndown(a.content)+'\n\nИсточник: '+a.url+'\n';const root=await this.directory(),file=path.join(root,safeName(a.title)+'-'+Date.now()+'.md');await fsp.writeFile(file,text);return{file,text};}
  async startNetwork(){const wc=this.wc();if(this.network.has(wc.id))return;const records=[];this.network.set(wc.id,records);if(!wc.debugger.isAttached())wc.debugger.attach('1.3');const handler=(_e,method,p)=>{if(!this.network.has(wc.id))return;if(method==='Network.requestWillBeSent'){const prev=records.find(r=>r.id===p.requestId);const redirects=prev?[...(prev.redirects||[]),{url:prev.url,status:p.redirectResponse?.status}]:[];if(prev)records.splice(records.indexOf(prev),1);records.unshift({id:p.requestId,url:p.request.url,method:p.request.method,requestHeaders:p.request.headers,status:null,start:p.timestamp,redirects});if(records.length>200)records.length=200;}if(method==='Network.responseReceived'){const r=records.find(r=>r.id===p.requestId);if(r)Object.assign(r,{status:p.response.status,responseHeaders:p.response.headers,mime:p.response.mimeType,timing:p.response.timing});}if(method==='Network.loadingFinished'){const r=records.find(r=>r.id===p.requestId);if(r){r.duration=Math.round((p.timestamp-r.start)*1000);r.bytes=p.encodedDataLength;}}if(method==='Network.loadingFailed'){const r=records.find(r=>r.id===p.requestId);if(r)r.error=p.errorText;}};this.networkHandlers.set(wc.id,handler);wc.debugger.on('message',handler);await wc.debugger.sendCommand('Network.enable',{maxTotalBufferSize:5*1024*1024,maxResourceBufferSize:512*1024});}
  networkList(){return (this.network.get(this.wc().id)||[]).map(({requestHeaders,responseHeaders,...r})=>r);}
  async networkDetail(id){const wc=this.wc(),r=this.network.get(wc.id)?.find(r=>r.id===id);if(!r)throw Error('Запрос больше не доступен.');const redact=headers=>Object.fromEntries(Object.entries(headers||{}).map(([k,v])=>[k,/authorization|cookie|token|api.key/i.test(k)?'••••':v]));let body='';try{const result=await wc.debugger.sendCommand('Network.getResponseBody',{requestId:id});body=result.base64Encoded?'Двоичный ресурс':result.body.slice(0,500000);}catch{body='Тело ответа не сохранено. Обновите страницу с включённой записью.';}return{...r,requestHeaders:redact(r.requestHeaders),responseHeaders:redact(r.responseHeaders),body};}
  stopNetwork(){const wc=this.wc();this.network.delete(wc.id);const handler=this.networkHandlers.get(wc.id);if(handler)wc.debugger.removeListener('message',handler);this.networkHandlers.delete(wc.id);if(wc.debugger.isAttached())wc.debugger.sendCommand('Network.disable').catch(()=>{});}
  detachAux(){for(const a of this.aux){try{this.win.contentView.removeChildView(a.view);}catch{}if(a.owned&&!a.view.webContents.isDestroyed())a.view.webContents.close({waitForBeforeUnload:false});}this.aux=[];}
  async responsivePreview(input){this.detachAux();this.splitId='';if(!input?.devices?.length){this.responsive=null;this.changed();return;}const devices=input.devices.slice(0,3).map(d=>({width:Math.max(240,Math.min(2560,Number(d.width)||390)),height:Math.max(320,Math.min(2560,Number(d.height)||844)),name:String(d.name||'Viewport').slice(0,30)})),wc=this.wc();for(const d of devices){const view=new WebContentsView({webPreferences:{session:wc.session,sandbox:true,contextIsolation:true,nodeIntegration:false}});view.webContents.setWindowOpenHandler(()=>({action:'deny'}));if(this.onKey)view.webContents.on('before-input-event',this.onKey);view.webContents.on('will-navigate',(e,url)=>{if(!/^https?:\/\//i.test(url))e.preventDefault();});await view.webContents.loadURL(this.tab().url);this.aux.push({view,owned:true,device:d});}this.responsive=devices;this.closePanel();this.changed();}
  split(id){this.detachAux();this.responsive=null;this.splitId=id||'';this.changed();}
  layout(bounds,hidden){if(hidden){for(const a of this.aux){try{this.win.contentView.removeChildView(a.view);}catch{}}return false;}if(this.responsive){const w=Math.floor(bounds.width/this.aux.length);for(let i=0;i<this.aux.length;i++){const a=this.aux[i],scale=Math.min(w/a.device.width,bounds.height/a.device.height,1);this.win.contentView.addChildView(a.view);a.view.setBounds({x:bounds.x+i*w,y:bounds.y,width:w-4,height:bounds.height});a.view.webContents.enableDeviceEmulation({screenPosition:a.device.width<600?'mobile':'desktop',screenSize:{width:a.device.width,height:a.device.height},viewSize:{width:a.device.width,height:a.device.height},deviceScaleFactor:1,scale});}return true;}if(this.splitId){const other=this.tabs.find(t=>t.id===this.splitId);if(!other||other.id===this.activeId()){this.splitId='';return false;}this.ensureView(other);if(other.view){if(!this.aux.some(a=>a.view===other.view)){this.detachAux();this.aux.push({view:other.view,owned:false});}this.win.contentView.addChildView(other.view);other.view.setBounds({x:bounds.x+Math.floor(bounds.width/2),y:bounds.y,width:Math.floor(bounds.width/2),height:bounds.height});}}return false;}
  async pip(){const wc=this.wc(),video=await wc.executeJavaScript('(()=>{const v=[...document.querySelectorAll("video")].find(v=>!v.paused)||document.querySelector("video");return v?{url:v.currentSrc,time:v.currentTime,paused:v.paused}:null})()');if(!video)throw Error('На странице нет видео.');if(!/^https?:\/\//.test(video.url)){await wc.executeJavaScript('document.querySelector("video").requestPictureInPicture()',true);return{native:true,message:'Для этого потока доступен стандартный PiP.'};}this.pipWindow?.destroy();this.pipSource=wc;const w=this.pipWindow=new BrowserWindow({width:480,height:310,minWidth:240,minHeight:160,alwaysOnTop:true,title:'Kernel · Видео',backgroundColor:'#000',webPreferences:{session:wc.session,sandbox:true,contextIsolation:true,nodeIntegration:false}});w.setAlwaysOnTop(true,'floating');w.webContents.setWindowOpenHandler(()=>({action:'deny'}));await w.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<!doctype html><style>html,body{margin:0;background:#000;width:100%;height:100%;overflow:hidden}video{width:100%;height:100%}</style><video autoplay controls src="'+escapeHTML(video.url)+'"></video>'));await w.webContents.executeJavaScript('(()=>{const v=document.querySelector("video");v.currentTime='+Number(video.time)+';v.play().catch(()=>{});})()',true);await wc.executeJavaScript('document.querySelector("video")?.pause()');w.on('closed',()=>{if(!wc.isDestroyed())wc.executeJavaScript('document.querySelector("video")?.play().catch(()=>{})').catch(()=>{});});return{native:false};}
  async action(name,input={}){const tab=this.tab();switch(name){
    case'info':return this.info();case'copy':return this.copy(input.text);case'folder':return shell.openPath(await this.directory());case'cancel':this.jobs.get(input.id)?.controller.abort();return;case'save':return this.savePage(input.mode||'snapshot');case'inspect':return this.inspect();case'copy-style':{const r=await this.inspect();if(r)return this.copy(input.kind==='tailwind'?r.tailwind:input.kind==='color'?r.style.color:input.kind==='font'?r.style['font-family']:r.css);return;}
    case'screenshot':return this.screenshot(input.kind||'full');case'pdf':return this.pdf(input.clean!==false);case'reader':{const a=await this.article(),wc=this.wc();await wc.executeJavaScript('(()=>{document.body.innerHTML='+JSON.stringify('<main style="max-width:760px;margin:40px auto;padding:0 24px;font:18px/1.8 Georgia;color:#ddd"><h1>'+escapeHTML(a.title)+'</h1>'+a.content+'</main>')+';document.head.querySelectorAll("style,link[rel=stylesheet]").forEach(e=>e.remove());document.body.style.cssText="background:#111;margin:0;color:#ddd";})()');return{message:'Режим чтения. Обновление страницы вернёт исходный вид.'};}
    case'assets':return(await this.snapshot()).assets;case'assets:download':{const allowed=(await this.snapshot()).assets,urls=input.urls?.slice(0,200)||[];const root=path.join(await this.directory(),'assets-'+Date.now());await fsp.mkdir(root,{recursive:true});let count=0;for(const url of urls){if(!allowed.some(a=>a.url===url)||!/^https?:\/\//.test(url))continue;const r=await this.wc().session.fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)continue;const size=Number(r.headers.get('content-length'));if(size>40*1024*1024)continue;const chunks=[];let n=0;for await(const c of r.body){n+=c.length;if(n>40*1024*1024)throw Error('Ресурс превышает 40 МБ.');chunks.push(c);}const file=path.join(root,require('./pure.cjs').assetName(url));await fsp.writeFile(file,Buffer.concat(chunks));count++;this.log('ASSET',path.basename(file));}return{folder:root,count};}
    case'colors':return invoke(this.wc(),page.palette);case'eyedropper':{this.closePanel();try{const r=await this.wc().executeJavaScript('new EyeDropper().open()',true);return this.copy(r.sRGBHex);}finally{this.openPanel('tools');}}case'fonts':return invoke(this.wc(),page.palette);case'links':return invoke(this.wc(),page.links);case'qr':{const selection=await this.wc().executeJavaScript('window.getSelection()?.toString()||""');const text=input.text||selection||tab.url;return{text,image:await QR.toDataURL(text,{width:256,margin:2,color:{dark:'#101112',light:'#ffffff'}})};}case'markdown':return this.markdown();
    case'note:get':return{url:tab.url,text:this.data.notes[tab.url]||''};case'note:save':this.data.notes[String(input.url||tab.url)]=String(input.text||'').slice(0,50000);this.save();return{saved:true};case'edit':return invoke(this.wc(),page.temporaryEdit);case'edit:css':return this.wc().executeJavaScript('(()=>{let s=document.getElementById("__kernel_edit_css");if(!s){s=document.createElement("style");s.id="__kernel_edit_css";document.head.append(s);}s.textContent='+JSON.stringify(String(input.css||'').slice(0,100000))+';})()');case'edit:image':{const r=await this.inspect();if(r&&/^https?:\/\//.test(input.url))await this.wc().executeJavaScript('(()=>{const e=window.__kernelPickedElement;if(e?.tagName==="IMG")e.src='+JSON.stringify(input.url)+';delete window.__kernelPickedElement;})()');return;}
    case'diff:save':{const p=await this.snapshot();this.data.snapshots[p.url]={text:p.text,at:Date.now()};this.save();return{saved:true};}case'diff':{const p=await this.snapshot(),old=this.data.snapshots[p.url];if(!old)throw Error('Сначала сохраните снимок для сравнения.');return{...textDiff(old.text,p.text),since:old.at};}case'json':{const text=input.text||await this.wc().executeJavaScript('document.body.innerText');return JSON.parse(text);}case'network:start':await this.startNetwork();return{started:true};case'network:list':return this.networkList();case'network:detail':return this.networkDetail(input.id);case'network:stop':this.stopNetwork();return;
    case'storage':return{...await invoke(this.wc(),page.storage),cookies:await this.wc().session.cookies.get({url:tab.url})};case'storage:clear':{const wc=this.wc();if(input.kind==='local')await wc.executeJavaScript('localStorage.clear()');else if(input.kind==='session')await wc.executeJavaScript('sessionStorage.clear()');else if(input.kind==='cookies'){for(const c of await wc.session.cookies.get({url:tab.url}))await wc.session.cookies.remove((c.secure?'https':'http')+'://'+c.domain.replace(/^\./,'')+c.path,c.name);}return{cleared:true};}
    case'redirects':{if(!input.url&&tab.redirects?.length)return [...tab.redirects,{url:tab.url,status:tab.finalHTTPStatus||null}];let url=input.url||tab.url;if(!/^https?:\/\//i.test(url))throw Error('Укажите HTTP или HTTPS URL.');const chain=[];for(let i=0;i<12;i++){const r=await this.wc().session.fetch(url,{method:'HEAD',redirect:'manual',signal:AbortSignal.timeout(15000)});chain.push({url,status:r.status});const next=r.headers.get('location');if(!next||r.status<300||r.status>=400)break;const u=new URL(next,url);if(!/^https?:$/.test(u.protocol))break;url=u.href;}return chain;}case'clean-url':return this.copy(cleanURL(tab.url));
    case'duplicates':{const groups=new Map();for(const t of this.tabs){const key=t.url.startsWith('http')?cleanURL(t.url).split('#')[0]:t.url;const list=groups.get(key)||[];list.push({id:t.id,title:t.title,url:t.url});groups.set(key,list);}return [...groups.values()].filter(g=>g.length>1);}case'sleep':{let count=0;for(const t of this.tabs)if(t.id!==this.activeId()&&!t.pinned&&t.view&&!t.view.webContents.isCurrentlyAudible()){this.suspend(t);count++;}this.changed();return{count};}
    case'workspace:save':{const entry={id:crypto.randomUUID(),name:safeName(input.name||'Workspace '+(this.data.workspaces.length+1)),at:Date.now(),tabs:this.tabs.map(t=>({url:t.url,title:t.title,pinned:t.pinned,route:this.connection.tabs.get(t.id)})),route:this.connection.workspace};this.data.workspaces.push(entry);this.save();this.changed();return entry;}case'workspace:restore':{const w=this.data.workspaces.find(w=>w.id===input.id);if(!w)throw Error('Workspace не найден.');this.connection.workspace=w.route||null;this.connection.save();const old=[...this.tabs],ids=w.tabs.map(t=>this.createTab(t.url,{...t,activate:false}));if(!input.append)for(const t of old)this.closeTab(t.id);this.selectTab(ids[0]);return{count:ids.length};}case'workspace:delete':this.data.workspaces=this.data.workspaces.filter(w=>w.id!==input.id);this.save();this.changed();return;
    case'responsive':return this.responsivePreview(input);case'split':this.split(input.id);return;case'focus':if(!this.focus){this.detachAux();this.responsive=null;this.splitId='';}this.focus=!this.focus;this.changed();return{enabled:this.focus};case'pip':return this.pip();case'pip:settings':if(this.pipWindow&&!this.pipWindow.isDestroyed()){this.pipWindow.setOpacity(Math.max(.2,Math.min(1,Number(input.opacity)||1)));this.pipWindow.setAlwaysOnTop(input.alwaysOnTop!==false);if(input.width)this.pipWindow.setSize(Math.max(240,Math.min(1920,Number(input.width))),Math.max(160,Math.min(1080,Number(input.height)||310)));}return;
    case'table-csv':{const text=await invoke(this.wc(),page.tableCSV);if(text===null)throw Error('Таблица не найдена.');const file=path.join(await this.directory(),'table-'+Date.now()+'.csv');await fsp.writeFile(file,'\ufeff'+text);return{text,file};}
    case'currency':{const from=String(input.from||'USD').toUpperCase(),to=String(input.to||'EUR').toUpperCase(),amount=Number(input.amount);if(!/^[A-Z]{3}$/.test(from)||!/^[A-Z]{3}$/.test(to)||!Number.isFinite(amount))throw Error('Неверная сумма или код валюты.');this.rateCache||=new Map();let data=this.rateCache.get(from);if(!data||Date.now()/1000>=data.time_next_update_unix){const response=await this.wc().session.fetch('https://open.er-api.com/v6/latest/'+from,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Сервис курсов недоступен.');data=await response.json();this.rateCache.set(from,data);}const rate=data.rates?.[to];if(!rate)throw Error('Валюта не поддерживается сервисом.');return{result:Math.round(amount*rate*1000000)/1000000,from,to,rate,updated:data.time_last_update_utc};}
    case'pip:return':if(this.pipWindow&&!this.pipWindow.isDestroyed()&&this.pipSource&&!this.pipSource.isDestroyed()){const time=await this.pipWindow.webContents.executeJavaScript('document.querySelector("video")?.currentTime||0');await this.pipSource.executeJavaScript('(()=>{const v=document.querySelector("video");if(v)v.currentTime='+Number(time)+';})()').catch(()=>{});}this.pipWindow?.close();this.win.show();this.win.focus();return;
    case'clipboard:clear':this.clipboard=[];return;case'convert':return{result:convert(input.kind,input.value)};case'archive':return this.data.archive;case'archive:open':{const r=this.data.archive.find(a=>a.id===input.id);if(r)return shell.openPath(r.file);return;}case'archive:folder':{const r=this.data.archive.find(a=>a.id===input.id);if(r)return shell.openPath(r.folder);return;}case'export':{const root=await this.directory(),file=path.join(root,safeName(input.name||'export.txt'));await fsp.writeFile(file,String(input.text||'').slice(0,10000000));return{file};}default:throw Error('Неизвестная утилита.');}
  }
  dispose(){this.live=false;for(const j of this.jobs.values())j.controller.abort();this.detachAux();if(this.pipWindow&&!this.pipWindow.isDestroyed())this.pipWindow.destroy();}
}
module.exports={ToolService,invoke};


